LICENSE.txt
README.md

Signed-off-by: Mike Chang <changml@amazon.com>

Readme and license changes

---

Gems/OpenXRVk/Code/Include/OpenXRVk/Platform/Linux/OpenXRVk_Linux.h

Fix OpenXRVk gem building on Linux.

---

.automatedtesting.json

case fix for case sensitive platforms

O3de extras ar fixes

---

Gems/XR/Code/Include/XR/XRInput.h

Signed-off-by: byrcolin <byrcolin@amazon.com>

fix device no found

---

Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkInput.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkUtils.h
Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp
Gems/XR/Code/Include/XR/XRBase.h

Added headers that appeared to be missing and moved some base headers.

OpenXR Misc header fixes

---

Templates/Multiplayer/template.json

Final Mutliplayer Template PR before creating a dev-branch release 1.0.
Fixed json to have the correct zip file name and updated the version hash.
Signed-off-by: Gene Walters <genewalt@amazon.com>

Latest Multiplayer Template Version Hash

---

Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkInstance.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkPhysicalDevice.h
Gems/OpenXRVk/Code/Source/OpenXRVkPhysicalDevice.cpp
Gems/XR/Code/Include/XR/XRInstance.h

Fixed compilation error in OpenXRVk gem

---

Projects/OpenXRTest/project.json

- Updating properties from their default values to something more meaningful.
Signed-off-by: amzn-phist <52085794+amzn-phist@users.noreply.github.com>

Update the OpenXRTest project.json

---

Projects/OpenXRTest/Assets/Room_DoorMAT.material

Fix Room_DoorMAT.material asset

---

Projects/OpenXRTest/Assets/Office_Table_DeskWoodMAT.material
Projects/OpenXRTest/Assets/Room.fbx
Projects/OpenXRTest/Levels/XR_Office/XR_Office.prefab

Signed-off-by: shawstar <shawstar@amazon.com>
Optimized Lights and removed blinds from windows

Optimized Lights and removed blinds from windows @shawstar

---

Projects/OpenXRTest/Gem/CMakeLists.txt

Signed-off-by: byrcolin <byrcolin@amazon.com>

update the unified alias

---

Gems/ROS2/Code/CMakeLists.txt

Updating ROS2 to include the Unified alias
Signed-off-by: puvvadar <puvvadar@amazon.com>

Update ROS2 cmake with Unified

---

Gems/OpenXRVk/Code/CMakeLists.txt
Gems/XR/Code/CMakeLists.txt

Adds the Unified alias to XR and OpenXRVk
Signed-off-by: puvvadar <puvvadar@amazon.com>

Add Unified alias to XR related Gems

---

Gems/ROS2/README.md

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>

Fix github repo links for the ROS2 Gem

---

Gems/ROS2/Code/Include/ROS2/Lidar/LidarRaycasterBus.h

removed invalid link and supplementary information

---

Gems/RosRobotSample/Assets/ROSbot.prefab

Adjust the viewport of the camera in the sample robot to the correct location.

Adjust camera position on ROSBot in RosRobotSample

---

Gems/OpenXRVk/Code/Include/OpenXRVk/InputDeviceXRController.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkDevice.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkInput.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkInstance.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkSession.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkSpace.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkSwapChain.h
Gems/OpenXRVk/Code/Source/OpenXRVkModule.cpp
Gems/OpenXRVk/Code/Source/Platform/Common/Default/OculusTouch_Default.h
Gems/ProteusRobot/Code/Source/Clients/ProteusRobotModule.cpp
Gems/ProteusRobot/Code/Source/ProteusRobotModuleInterface.h
Gems/ProteusRobot/Code/Source/Tools/ProteusRobotEditorModule.cpp
Gems/ROS2/Code/Source/ROS2EditorModule.cpp
Gems/ROS2/Code/Source/ROS2Module.cpp
Gems/ROS2/Code/Source/ROS2ModuleInterface.h
Gems/XR/Code/Include/XR/XRDevice.h
Gems/XR/Code/Include/XR/XRFactory.h
Gems/XR/Code/Include/XR/XRInput.h
Gems/XR/Code/Include/XR/XRInstance.h
Gems/XR/Code/Include/XR/XRSession.h
Gems/XR/Code/Include/XR/XRSpace.h
Gems/XR/Code/Include/XR/XRSwapChain.h
Gems/XR/Code/Include/XR/XRSystem.h
Gems/XR/Code/Source/XRModule.cpp
Projects/OpenXRTest/Gem/Source/OpenXRTestModule.cpp
Templates/Multiplayer/Template/Gem/Code/Source/${Name}Module.cpp
Templates/Ros2ProjectTemplate/Template/Gem/Source/${Name}Module.cpp

as [14530](https://github.com/o3de/o3de/pull/14530), sync modifications.

Remove unused 3rd parameter for AZ_CLASS_ALLOCATOR.

---

Gems/ROS2/Assets/Passes/PipelineRenderToTextureROSColor.pass
Gems/ROS2/Code/Source/Camera/CameraSensor.cpp
Gems/ROS2/Code/Source/Camera/CameraSensor.h
Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp
Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.h
Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.h

The RGBD sensor is running only one pipeline with this change.
Plan :
Signed-off-by: Michał Pełka <michal.pelka@robotec.ai>

Rework RGBD sensor.

---

Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp

Fixes #216.
Change is logical for me, you can see in plots that it behaves as expected.

Fix bug with wheel base handling in Vehicle Dynamics in ROS 2.

---

Gems/ProteusRobot/Assets/Proteus.prefab

Proteus Gem - update for the camera sensor in prefab

---

Gems/Blast/Code/Include/Blast/BlastActor.h
Gems/Blast/Code/Source/Editor/EditorBlastMeshDataComponent.cpp
Gems/Blast/Code/Source/Family/ActorRenderManager.cpp
Gems/Blast/Code/Source/Family/ActorRenderManager.h
Gems/Blast/Code/Source/Family/BlastFamily.h
Gems/Blast/Code/Tests/ActorRenderManagerTest.cpp
Gems/Blast/Code/Tests/BlastActorTest.cpp
Gems/Blast/Code/Tests/BlastFamilyTest.cpp
Gems/Blast/Code/Tests/DamageManagerTest.cpp
Gems/Blast/Code/Tests/Mocks/BlastMocks.h

Fixes https://github.com/o3de/o3de/issues/15445
Fixed Blast unit tests as well. They pass successfully.

Fixed compilation error in blast experimental gem

---

Gems/XR/Code/Include/XR/XRSystemComponent.h
Gems/XR/Code/Source/XRSystem.cpp
Gems/XR/Code/Source/XRSystemComponent.cpp

Make sure RHI backends are loaded before XR modules

Add RHIService a dependent of XRSystem

---

Templates/Multiplayer/template.json

Added a new release zip, and updating the sha256 in the branch to match.
Fixes https://github.com/o3de/o3de/issues/14968

Multiplayer Template Zip Fix

---

Gems/ROS2/Code/Source/ROS2SystemComponent.h

Included mainpage for the API Reference documentation. Fixes #232

Documentation mainpage

---

Gems/WarehouseSample/Assets/O3DEScene/Prefabs/Warehouse.prefab
Templates/Ros2ProjectTemplate/Template/Levels/DemoLevel/DemoLevel.prefab

Updated:
- In WarehouseSampe gem: turned on cached shadows and changed shadow filter 
- In Ros2ProjectTemplate: removed artifacts (unused lights), updated env lightning and camera settings
Fps changed from 33 to 88 in a configuration similar to #261
This addresses #261

Ros2ProjectTemplate performance fix

---

Gems/ProteusRobot/gem.json
Gems/WarehouseSample/gem.json

Add Proteus Gem description and missing links

---

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp

I've added a simple check for success of prefab creation. This fixes #286.

Add check for prefab creation success

---

Gems/ROS2/Code/Source/Camera/CameraConstants.h
Gems/ROS2/Code/Source/Camera/CameraPublishers.cpp
Gems/ROS2/Code/Source/Camera/CameraPublishers.h
Gems/ROS2/Code/Source/Camera/CameraSensor.cpp
Gems/ROS2/Code/Source/Camera/CameraSensor.h
Gems/ROS2/Code/Source/Camera/CameraSensorDescription.cpp
Gems/ROS2/Code/Source/Camera/CameraSensorDescription.h
Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp
Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.h
Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
Gems/ROS2/Code/ros2_files.cmake

Improve code encapsulation, separation of concern, reusability etc. in Camera sensor classes.
This also adds camera_info publishing synchronization with the image topics.

Camera classes refactoring

---

Gems/ROS2/Code/Include/ROS2/Utilities/ROS2Conversions.h
Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.cpp
Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h
Gems/ROS2/Code/Source/Utilities/ROS2Conversions.cpp

Solves https://github.com/o3de/o3de-extras/issues/336 
This will add a variance setting through the Editor and publish in the covariance matrix in ros2 sensor_msg::imu.

Add imu covariance setting

---

Gems/ROS2/Code/Source/Camera/CameraUtilities.cpp
Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp
Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h
Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.h
Gems/ROS2/Code/Source/Manipulation/JointMotorControllerComponent.cpp
Gems/ROS2/Code/Source/Manipulation/JointPublisherComponent.cpp
Gems/ROS2/Code/Source/Manipulation/ManipulatorControllerComponent.cpp
Gems/ROS2/Code/Source/Manipulation/PidMotorControllerComponent.cpp
Gems/ROS2/Code/Source/Utilities/ROS2Conversions.cpp
Gems/ROS2/Code/Source/VehicleDynamics/Utilities.h

Fixes compilation errors and adds copyrights to some files contributed earlier.

compilation fixes and added missing copyrights

---

Gems/ROS2/Code/Source/ProximitySensor/ROS2ProximitySensor.cpp
Gems/ROS2/Code/Source/ProximitySensor/ROS2ProximitySensor.h
Gems/ROS2/Code/Source/ROS2ModuleInterface.h
Gems/ROS2/Code/ros2_files.cmake

I've added a Proximity sensor that uses raycasting to determine if an object exists in front of it. This addresses #363.

Add proximity sensor

---

Gems/ROS2/Code/Include/ROS2/Lidar/LidarRaycasterBus.h
Gems/ROS2/Code/Include/ROS2/Lidar/LidarRegistrarBus.h
Gems/ROS2/Code/Include/ROS2/Lidar/LidarSystemBus.h
Gems/ROS2/Code/Source/Lidar/LidarSystem.cpp
Gems/ROS2/Code/Source/Lidar/LidarSystem.h
Gems/ROS2/Code/Source/Lidar/LidarTemplate.cpp
Gems/ROS2/Code/Source/Lidar/LidarTemplate.h
Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp
Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.h
Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h

This pull request includes the following changes related to this [update of the RGL gem.](https://github.com/RobotecAI/o3de-rgl-gem/pull/5):
1. Support for lidar side publication
- configuration of the lidar-side publisher
- timestamp provision
2. Updated Noise handling
- noise disabling
- 2D lidar noise

ROS2: Allow for Lidar-side PointCloud publication and update Noise handling. 

---

Gems/ROS2/Code/Source/Gripper/GripperActionServer.cpp
Gems/ROS2/Code/Source/Gripper/GripperActionServerComponent.cpp
Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp

Fixes #423 and was tested against non-unity builds.

Fix missing include in JointsTrajectoryComponent.cpp

---

Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponent.cpp
Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponentConfiguration.cpp

Missing asset builder header, moved static to internal

Fix to conveyor belt compilation

---

Gems/ROS2/Code/Source/ContactSensor/ROS2ContactSensorComponent.cpp

Added missing header to contact sensor

---

Gems/ROS2/Code/Include/ROS2/Lidar/LidarRaycasterBus.h
Gems/ROS2/Code/Source/Lidar/Lidar2DSensorConfiguration.cpp
Gems/ROS2/Code/Source/Lidar/Lidar2DSensorConfiguration.h
Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp
Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h
Gems/ROS2/Code/Source/Lidar/LidarSensorConfiguration.cpp
Gems/ROS2/Code/Source/Lidar/LidarSensorConfiguration.h
Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp
Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp

Solves issue https://github.com/o3de/o3de-extras/issues/138

Added the ability for lidars to ignore multiple layers

---

Gems/ROS2/Code/Source/ROS2ModuleInterface.h
Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.cpp
Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.h
Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraConfiguration.cpp
Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraConfiguration.h
Gems/ROS2/Code/ros2_files.cmake

The component that allows switching camera and smoothing.
It will enable aggregating entities that transform and can be used to set the camera's viewpoint.

Added util to manipulate cameras.

---

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp

Add a check if URDF was parsed successfully. Fixes #474 .

Add validation for parsing URDF

---

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.cpp

Fixes #490.
Added presentation of sdf messages:

Added presentation of sdf messages

---

Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.cpp

Fixes https://github.com/o3de/o3de-extras/issues/510.
Each tag inside `inertia` is checked and the value is set to default if missing.
Before this change importing this robot (https://github.com/RobotnikAutomation/rbvogui_common/blob/melodic-devel/rbvogui_description/robots/rbvogui_std_ur10.urdf.xacro) results in missing wheels:
Wheel links are not modified:
After this change, the wheels are visible:
Wheel links are modified:

fix incomplete inertial tags in urdfs before import

---

Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.cpp
Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.h
Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
Gems/ROS2/Code/Source/RobotImporter/xacro/XacroUtils.cpp
Gems/ROS2/Code/Source/RobotImporter/xacro/XacroUtils.h

I forgot that we support XACRO implementing #481.
Resolves issue #528.

Enable fixing in memory URDFs generated from XACRO

---

Gems/ROS2/Code/Source/Lidar/LidarCore.cpp
Gems/ROS2/Code/Source/Lidar/LidarSensorConfiguration.h

This PR solves #508 (configuration issue) both for all lidars.

Fix lidar components

---

Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkDevice.h
Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkSystemComponent.h
Gems/OpenXRVk/Code/Source/OpenXRVkDevice.cpp
Gems/OpenXRVk/Code/Source/OpenXRVkSession.cpp
Gems/OpenXRVk/Code/Source/OpenXRVkSystemComponent.cpp
Gems/XR/Assets/Passes/FoveatedImage.pass
Gems/XR/Assets/Passes/OpenXRPassTemplates.azasset
Gems/XR/Code/CMakeLists.txt
Gems/XR/Code/Include/XR/XRPassRegisterSystemComponent.h
Gems/XR/Code/Include/XR/XRSystem.h
Gems/XR/Code/Source/Passes/FoveatedImagePass.cpp
Gems/XR/Code/Source/Passes/FoveatedImagePass.h
Gems/XR/Code/Source/XRModule.cpp
Gems/XR/Code/Source/XRPassRegisterSystemComponent.cpp
Gems/XR/Code/Source/XRSystem.cpp
Gems/XR/Code/xr_private_common_files.cmake

Bringing over https://github.com/o3de/o3de-extras/pull/479 to stab branch

Pulling over OpenXr fixes from dev to stab branch

---

Gems/ROS2/gem.json
repo.json

This PR cherry picks the changes made to development in this PR https://github.com/o3de/o3de-extras/pull/545

Cherry pick ROS2 remote gem update from development

---

Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp
Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.cpp
Gems/ROS2/Code/Source/Utilities/ArticulationsUtilities.cpp
Gems/ROS2/Code/Source/Utilities/ArticulationsUtilities.h
Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/AckermannDriveModel.cpp
Gems/ROS2/Code/Source/VehicleDynamics/Utilities.cpp
Gems/ROS2/Code/Source/VehicleDynamics/WheelDynamicsData.h

Added support for articulations in the Ackermann drive model.

Added support for articulations in the Ackermann drive model

---

Gems/RosRobotSample/Assets/ROSBot_slamtec.prefab
Gems/RosRobotSample/Assets/ROSbot_velodyne.prefab

Identical issue to https://github.com/o3de/o3de-extras/pull/562.

Fix missing filtering to Rosbot Lidar.

---

Templates/Ros2RoboticManipulationTemplate/Template/Examples/panda_moveit_config_demo.launch.py
Templates/Ros2RoboticManipulationTemplate/Template/project.json

Fix to template to enable missing gem.

Enabled Warehouse Automation gem in Ros2RoboticManipulation Template

---

Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp
Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.h
Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
Gems/ROS2/gem.json
Templates/Ros2RoboticManipulationTemplate/Template/Examples/panda_moveit_config_demo.launch.py
Templates/Ros2RoboticManipulationTemplate/Template/project.json
repo.json

Merged `stabilization/2310` to `development`
CONFLICTS:
Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp
- Took stabilization change
Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
- Took stabilization change
Templates/Ros2RoboticManipulationTemplate/Template/Examples/panda_moveit_config_demo.launch.py
- Took stabilization change
repo.json
- Took stabilization change

Merged `stabilization/2310` to `development`

---

Gems/WarehouseAutomation/Code/Source/ConveyorBelt/ConveyorBeltComponent.cpp
Gems/WarehouseAutomation/Code/Source/ConveyorBelt/ConveyorBeltComponent.h

A change to test for increased stability due to crashes in contacts processing in physics.

Change kinematic update to pre-simulation

---

Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp

Cherry-pick PR #524 which adds import optimization settings for OBJ files. 
Tested by importing OBJ files in the point-release branch and verifying that the import settings were correctly applied.

Cherry-pick - Add import optimization settings for obj files. (#524)

---

Gems/ROS2/Code/Source/RobotImporter/URDF/ArticulationsMaker.cpp
Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/AckermannDriveModel.cpp
Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp
Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h
Gems/ROS2/Code/Source/VehicleDynamics/Utilities.cpp
Gems/ROS2/Code/Source/VehicleDynamics/Utilities.h
Gems/ROS2/Registry/articulations.setreg

Support for skid-steering and articulations, fix limit handling with URDF import.

Support for skid-steering and articulations.

---

Gems/ROS2/Code/Source/Spawner/ROS2SpawnPointComponentController.cpp
Gems/ROS2/Code/Source/Spawner/ROS2SpawnPointEditorComponent.cpp
Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponentController.cpp
Gems/ROS2/Code/Source/Spawner/ROS2SpawnerEditorComponent.cpp

I've changed how the spawn point component and spawner component render in the editor. Resolves #600.

Change reflect in spawn points

---

Gems/ROS2/Code/Source/Utilities/Controllers/PidConfiguration.cpp

Merges the point release branch to main
Testing was performed in the point release branch

Merge point-release/23102 branch to main

---

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp

Closes #653 
This PR fixes issue with spawner names (the same iterator was reused), additionally, the service to get spawnable names was renamed `get_available_spawnable_namespawnable_names` -> `get_available_spawnable_names`.
40 spawnables (out of 3) were spawned successfully with the following script:
```bash
#!/bin/bash
NAMES=("nomesh" "box" "ack")
for i in {1..40} ; do
NAME=${NAMES[$(($RANDOM % 3))]}
echo ""
echo "***** ${NAME} *****"
sleep 3
ros2 service call /spawn_entity gazebo_msgs/srv/SpawnEntity "{name: ${NAME}}"
done
```

fix spawner; rename spawner service

---

Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2AckermannModelHook.cpp
Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2CameraSensorHook.cpp
Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2ImuSensorHook.cpp
Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2LidarSensorHook.cpp
Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2SkidSteeringModelHook.cpp
Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp

Fix #658.
Manually importing robots to the O3DE.

Change Ros2FrameComponent to Ros2FrameEditorComponent in urdf/sdf hooks

---

Gems/ProteusRobot/Assets/Proteus.prefab

I've fixed the broken steering in the Proteus robot by changing the TrackBase. (additionally, O3DE automatically changed some values)
Manually importing and driving the robot.

Fix broken steering for Proteus robot

---

Gems/XR/Code/Source/XRSystem.cpp

Fixes necessary for https://github.com/o3de/o3de/pull/17974
On Windows.

Multi-device-resources fix for the XR system

---

Gems/ROS2/Code/Include/ROS2/Communication/TopicConfiguration.h

Adds QoS constructor.
Tested on locally modified ROS2 GEM, setting different QoS to imported sensors.

TopicConfiguration: added QoS constructor

---

Templates/Multiplayer/Template/project.json

Remove Hardcoded Values from Multiplayer Project Template Project.json
How was this PR tested?
Created a new project using Multiplayer Template
- Played multiplayer from Editor.exe using "DefaultLevel"
- Played multiplayer from ServerLauncher.exe and 2 GameLauncher.exes

Remove Hardcoded Values from Multiplayer Project Template Project.json

---

Gems/ROS2/Code/Source/VehicleDynamics/Utilities.cpp

Enables release build.
Release build.

Add maybe_unused to variable that is used in non-release macro

---

Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.cpp

This PR fixes a segmentation fault when importing a robot with the incorrect mapping of ROS 2 topics. In particular, the crash happens when the mapping is empty. The empty mapping can occur when topics are parametrized in xacro, but the variable is not set before the import. One of the examples is Turtlebot4, described in our [tutorial](https://development--o3deorg.netlify.app/docs/user-guide/interactivity/robotics/importing-robot/importing-turtlebot4/)
The error is caused by the line:
```cpp
std::string contentValue = content.GetValue()->GetAsString();
```
in which `content.GetValue()` is a nullptr for the following URDF input:
```
<ros>
<namespace/>
</ros>
```
Calling `GetAsString();` crashes O3DE.
Turtlebot was correctly imported, and some internal tests were implemented. The tests …

Check for nullptr in ROS topic mappings parser

---

Gems/OpenXRVk/gem.json
Gems/ROS2/gem.json
Gems/RosRobotSample/gem.json
Gems/XR/gem.json
Templates/Ros2FleetRobotTemplate/template.json
repo.json

Updates the repo.json for o3de-extras for the 2409 release
Locally tested

repo.json updates for release 2409

---

Projects/OpenXRTest/project.json
Templates/Multiplayer/template.json
Templates/Ros2ProjectTemplate/template.json
repo.json

Bumps the version for the ROS2 Project template since there were updates since the last version (2.0.0)
TBD

Update ros2 template package

---

Gems/ROS2/Code/Source/Camera/CameraSensor.cpp
Templates/Ros2FleetRobotTemplate/Template/Registry/ros2.setreg
Templates/Ros2FleetRobotTemplate/template.json
Templates/Ros2ProjectTemplate/Template/Registry/ros2.setreg
Templates/Ros2ProjectTemplate/template.json
Templates/Ros2RoboticManipulationTemplate/Template/Registry/ros2.setreg
Templates/Ros2RoboticManipulationTemplate/template.json

Introduce registry setting to enable pipeline modification for the camera sensor.
run against roscon2023 demo.

Registry setting for pipeline modification.

---

repo.json

Update the last-updated field to reflect valid date of update

Update 'last_updated' field

---

Gems/ROS2/Code/Source/Camera/CameraSensor.cpp

Changes a class name by adding interface.
By compiling the code and creating a scene with the ros2 camera and fog.

Fix compilation error - Change postprocess feature processor to interface

---

Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp

This PR fixes error that applied linear velocity as rotation velocity.
Manual test with tool https://github.com/michalpelka/q_simulation_interfaces

Adjust state applying 

---

Gems/SimulationInterfacesROS2/Code/Source/Clients/SimulationInterfacesROS2SystemComponent.cpp
Gems/SimulationInterfacesROS2/Code/Source/Clients/SimulationInterfacesROS2SystemComponent.h
Gems/SimulationInterfacesROS2/Code/Source/Services/StepSimulationServiceHandler.cpp
Gems/SimulationInterfacesROS2/Code/Source/Services/StepSimulationServiceHandler.h
Gems/SimulationInterfacesROS2/Code/Tests/Tools/InterfacesTest.cpp
Gems/SimulationInterfacesROS2/Code/simulationinterfacesros2_private_files.cmake

Added simulation step service 
Test with q_simulation_interfaces.

[Simulation Interfaces]  step simulation service

---

Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp
Gems/SimulationInterfaces/Code/Source/Clients/SimulationManager.cpp
Gems/SimulationInterfacesROS2/Code/Source/Actions/SimulateStepsActionServerHandler.cpp

Adjust capabilities.
Check response

[Simulation Interfaces] Adjust capabilities

---

Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp

I've used SimulatedBodyComponentRequests to set state. 
- built test

[Simulation Interfaces] Use simulated body request

---

Gems/OpenXRVk/Assets/Devices/Generic/Animations/LeftControllerAnimGraph.animgraph
Gems/OpenXRVk/Assets/Devices/Generic/Animations/LeftControllerMotionSet.motionset
Gems/OpenXRVk/Assets/Devices/Generic/Animations/RightControllerAnimGraph.animgraph
Gems/OpenXRVk/Assets/Devices/Generic/Animations/RightControllerMotionSet.motionset
Gems/OpenXRVk/Assets/Devices/Generic/Prefabs/Controllers.prefab
Gems/OpenXRVk/Assets/Devices/Generic/Prefabs/LeftController.prefab
Gems/OpenXRVk/Assets/Devices/Generic/Prefabs/RightController.prefab
Gems/OpenXRVk/Assets/OpenXRVk/Materials/RayInteractor.material
Gems/OpenXRVk/Assets/OpenXRVk/Models/ray.fbx
Gems/OpenXRVk/Assets/OpenXRVk/Prefabs/RayInteractor.prefab

Uploads the assets missing from PR 903.
Note that the original author has no write access for LFS. I'm uploading these assets on their behalf.
see https://github.com/o3de/o3de-extras/pull/903 for the code that goes with these assets.
Not tested - I have no VR controllers.  But the author split 903 into code and assets, these are the assets.
There is no code in this commit.

Assets for the VR controller setup

---

Gems/ROS2RobotImporter/Registry/sceneassetimporter.setreg

The DAE support was enabled in deleted registry setting.
Against project that has robot with DAE files in their URDF.

Bring back DAE

---

Gems/WarehouseAssets/Assets/Prefabs/WarehouseScene_small.prefab

Fixed one more assets that was missed in #932 , namely warehouse small scene asset:
- updated EditorMaterialComponent of Ceiling and Gate elements to ensure the slot is configured correctly (in case of Gate it was removed and added again)
- removed disabled elements of the second Gate (there is no second gate in a small warehouse)
Level with this asset was created. An asset was visually verified and RGL was used to check for errors.

Fix warehouse_small scene

---

Templates/Ros2RoboticManipulationTemplate/Template/Assets/Room/Textures/Desk/Room_M_Desk_Height.png
Templates/Ros2RoboticManipulationTemplate/Template/Assets/Room/Textures/Floor/plane_divided_DefaultMaterial_Height.png
Templates/Ros2RoboticManipulationTemplate/template.json

Fix missing texture in template
I've backported fixes from generated project to template

Fix missing textures in manipulator template

---

Gems/ROS2/Code/Source/Clock/ROS2ClockSystemComponent.cpp
Gems/ROS2/Code/Source/Clock/ROS2ClockSystemComponent.h

Fix compilation issue introduced in #944

Fix compilation error in ROS 2 gem

---

Gems/ROS2/gem.json

This PR bumps version of backported ROS2 Gem. Backported version has additional features which were required by Simulation Interfaces Gem 
not applicable

[Backports] ROS2 Gem Version Bump 
