Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp
NOTE: Needs this o3de PR https://github.com/o3de/o3de/pull/11329
=> Remove ConverFormat code duplication and import it from RHI Vulkan Reflect Conversion header.

Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkSession.h, Gems/OpenXRVk/Code/Source/OpenXRVkDevice.cpp, Gems/OpenXRVk/Code/Source/OpenXRVkPhysicalDevice.cpp
Fixes https://github.com/o3de/o3de/issues/11254
- Fixed issue when calling to `LoadProcAddresses` using intance, device and physical device.
- Followed the same vulkan flag usage as in hello_xr sample, now using `XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR` flag because we are using the other legacy vulkan flags from the sample too `XR_KHR_VULKAN_ENABLE_EXTENSION_NAME` and `XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR`.
- Simplified `EnumerateDeviceList` function.
=> Fixes for OpenXR vulkan initialization.

Projects/OpenXRTest/Gem/enabled_gems.cmake
Since OpenXRTest was created the `DiffuseProbeGrid` gem was enabled in new projects by default and therefore missing in OpenXRTest  (which is suppose to be a default project + XR gems).
=> Added missing DiffuseProbeGrid gem in OpenXRTest.

Templates/Multiplayer/template.json
- Template zip hash lowercase to work with latest engine release. (See https://github.com/o3de/o3de/issues/12443)
- Removed git files from the template manifest; these files don’t exist and so project creation stops prematurely leaving only a partial project.
Signed-off-by: Gene Walters <genewalt@amazon.com>
=> Update Multiplayer Template Hash To Work with Project Manager

Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp, Gems/XR/Code/Source/XRSystemComponent.cpp
The setting can make use of platform prefixes to only target one platform, for example:
````
{
"O3DE": {
"Atom": {
"OpenXR": {
"android_ViewResolutionScale": 0.5
}
}
}
}
````
NOTE: This setting is a temporary measure that will help to control the performance when running on Quest 2 by lowering the resolution. Further optimizations to make the VR pipeline more performant overall will be done in the future.
=> Added setting to be able to scale the resolution of OpenXR views

Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkInstance.h, Gems/OpenXRVk/Code/Source/OpenXRVkDevice.cpp, Gems/OpenXRVk/Code/Source/OpenXRVkInstance.cpp, Gems/XR/Code/Include/XR/XRInstance.h, Gems/XR/Code/Source/XRInstance.cpp
ASV RHI and RPI samples crashed when running on Quest2 with GPU detailed profiling mode enabled (`'adb shell ovrgpuprofiler -e`), which allows the use of `GPU systrace` and `ovrgpuprofiler` tools.
- XR pipeline calling `LoadProcAddresses` passing the physical device leads to vulkan extensions enabled when they are not supported in an XR environment.
- For better debugging now XR Device and Instance now printing their extensions when validation is enabled.
This PR goes in conjunction with this PR in o3de: https://github.com/o3de/o3de/pull/12559
Run ASV RHI and RPI samples on Quest 2 with GPU detailed profiling mode enabled and disabled.
Able to capture render stage metrics with both `GPU systrace` and `ovrgpuprofiler` tools.
=> Fix crash when running on Quest 2 with GPU detailed profiling mode enabled

Gems/OpenXRVk/Code/Source/OpenXRVkDevice.cpp
Running OpenXR on host platforms, where the rendering in done over the PC's GPU, the vulkan context created from XR will be used for the PC version and it needs to to gather its features' functions supported by the physics devices features. It was crashing because although its physical device reported raytracing support, the context didn't load the vulkan ray tracing functions.
=> Fix crash running editor/launcher on Quest 2 over link cable

Gems/XR/Code/Include/XR/XRSystem.h, Gems/XR/Code/Include/XR/XRSystemComponent.h, Gems/XR/Code/Source/XRSystem.cpp, Gems/XR/Code/Source/XRSystemComponent.cpp
Also fixed crash when shutting down launcher, the xr system needs to be destroyed on the xr system component deactivation, holding it until its destructor is too late.
=> Added functions to Xr Sytem to query if default rendered is needed

Gems/OpenXRVk/Code/CMakeLists.txt, Gems/OpenXRVk/Code/Source/XRCameraMovementComponent.cpp, Projects/OpenXRTest/Levels/XR_Office/XR_Office.prefab
- Asset Processor was processing the XRCameraMovement component, but with a warning.  This caused the Camera entity to not have this component when spawned at runtime.
- The issue was that the OpenXRVk Gem's cmake didn't declar an alias for the .Builders variant.
- Also fixed some stuff on the Edit Context and re-saved the XR_Office level.
=> Fixes an issue with camera movement in Launcher

Projects/OpenXRTest/Levels/XR_Office/XR_Office.prefab
- These components were broken after latest update.
- Adding XRCameraMovement.
- Adding and disabling FlyCameraInput.
Signed-off-by: amzn-phist <52085794+amzn-phist@users.noreply.github.com>
=> Adding back the XR camera components to XR_Office

Projects/OpenXRTest/Levels/XR_Office/XR_Office.prefab, Projects/OpenXRTest/Registry/OpenXR.setreg
Fixes https://github.com/o3de/o3de-extras/issues/61
Also setting OpenXR `ViewResolutionScale` to `0.75` for Android (1080p) to deliver stable 24 FPS in `Default_Level` and 12 FPS in `XR_Office`.
=> Removed sun entity from XR_Office level.

Gems/XR/Code/Source/XRSystem.cpp
Checking for null to avoid an editor and level crash when opening the OpenXRTest project.
Fixes #82
_Note: Maybe the warnings should actual be an error since I'm guessing some feature is fundamentally broken if these are null. although not yet sure how to properly fix the issue. A better error/warning should include more information; I'll defer to the experts._
=> Open XR Editor Crash Fix

Templates/Multiplayer/template.json
Adding NetworkRigidBodyCube.prefab to the template.json so that it's captured when making a new project
Fixes #63
Signed-off-by: Gene Walters <genewalt@amazon.com>
=> Multiplayer Template: Include NetworkRigidBodyCube.prefab 

Gems/WarehouseSample/Assets/O3DEScene/Prefabs/Warehouse.prefab, Projects/OpenXRTest/Levels/DefaultLevel/DefaultLevel.prefab, Templates/Multiplayer/Template/Levels/Demo/Demo.prefab
**IMPORTANT: Please approve but DO NOT merge this PR yet!** 
@moraaar will merge it once the work in [PhysX_StaticRigidBody_Staging](https://github.com/aws-lumberyard-dev/o3de/tree/PhysX_StaticRigidBody_Staging) branch is in o3de/development.
More information about this update here: https://github.com/o3de/o3de/pull/14261
What's been updated:
- Prefabs in OpenXRTest project.
- Prefabs in WarehouseSample gem.
- Prefabs in Multiplayer template.
=> Updated prefabs to follow new pattern that colliders require a rigid body.

Gems/ROS2/README.md
Signed-off-by: Adam Dąbrowski <adam.dabrowski@robotec.ai>
Clarify that the Gem does not work with a release (installed) O3DE.
The goal of this change is to help users to avoid running into issues such as https://github.com/o3de/o3de-extras/issues/115.
=> Add that the Gem does not work with the Release

Gems/ROS2/Code/Include/ROS2/Lidar/LidarRaycasterBus.h, Gems/ROS2/Code/Include/ROS2/Lidar/LidarRegistrarBus.h, Gems/ROS2/Code/Include/ROS2/Lidar/LidarSystemBus.h, Gems/ROS2/Code/Include/ROS2/ROS2Bus.h, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h, Gems/ROS2/Code/Source/Lidar/LidarRegistrarEditorSystemComponent.cpp, Gems/ROS2/Code/Source/Lidar/LidarRegistrarEditorSystemComponent.h, Gems/ROS2/Code/Source/Lidar/LidarRegistrarSystemComponent.cpp, Gems/ROS2/Code/Source/Lidar/LidarRegistrarSystemComponent.h, Gems/ROS2/Code/Source/Lidar/LidarSystem.cpp, Gems/ROS2/Code/Source/Lidar/LidarSystem.h, Gems/ROS2/Code/Source/Lidar/LidarTemplate.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplate.h, Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.h, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h, Gems/ROS2/Code/Source/ROS2EditorModule.cpp, Gems/ROS2/Code/Source/ROS2ModuleInterface.h, Gems/ROS2/Code/Source/ROS2SystemComponent.cpp, Gems/ROS2/Code/Source/ROS2SystemComponent.h, Gems/ROS2/Code/ros2_editor_files.cmake, Gems/ROS2/Code/ros2_files.cmake, Gems/ROS2/Code/ros2_header_files.cmake
This pull request introduces lidar implementation modularity by allowing for multiple LiDAR implementations to be added and used by the ROS2LidarSensor. This can be done by implementing the Lidar System and Raycaster interfaces either in the form of a new Gem or within the ROS Gem.  
Only manual tests of the new Lidar functionalities have been done.
=> Add lidar modularity for ROS2 Gem

Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp, Gems/ROS2/Code/Source/Lidar/LidarRegistrarSystemComponent.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplate.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.cpp
Fix missing `#includes` in .cpp files that were hidden by unity builds, such as:
```
usr/local/src/github/o3de-extras/Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp:93:68: error: no template named 'make_shared' in namespace 'AZStd'; did you mean 'std::make_shared'?
AZStd::shared_ptr<AzPhysics::RayCastRequest> request = AZStd::make_shared<AzPhysics::RayCastRequest>();
^~~~~~~~~~~~~~~~~~
std::make_shared
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:875:5: note: 'std::make_shared' declared here
make_shared(_Args&&... __args)
^
/usr/local/src/github/o3de-extras/Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp:93:68: error: no template named 'make_shared' in namespace 'AZStd'; did you mean 'std::make_shared'?
AZStd::shared_ptr<AzPhysics::RayCastRequest> …
```
=> Fix compilation errors for no-unity builds

Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameComponent.h, Gems/ROS2/Code/Source/Frame/ROS2FrameComponent.cpp
- Previously, it did not work well with intermediate entities without ROS2Frame component.
- For example, the prefab container entity.
- This resulted in skipping prefab transform and publishing invalid /tf
Fixes #139
=> A fix for ROS2Frame component

.github/ISSUE_TEMPLATE/ar_bug_report.md.txt, .github/ISSUE_TEMPLATE/bug_template.md.txt, .github/ISSUE_TEMPLATE/config.yml.txt, .github/ISSUE_TEMPLATE/deprecation_template.md.txt, .github/ISSUE_TEMPLATE/feature_request.md.txt
The main O3DE repository uses issue templates to guide the structure and contents of issues. This PR introduces these issue templates to the o3de-extras repo as well.
=> Migrate issue templates from main O3DE repository

Gems/ROS2/Code/Source/Odometry/ROS2OdometrySensorComponent.cpp
Added ROS2Frame as required service for ROS2OdometrySensor.
Added Assert after getting component to prevent segfault without indication to cause.
Fix for Issue 196
=> Made ROS2Frame required for ROS2Odometry to prevent possible crash on run

Gems/Blast/Editor/Scripts/blast_chunk_processor.py
Fixed an issue with python builder script connecting to an ebus before calling add_callback
Fixes https://github.com/o3de/o3de/issues/14209
Tested by manually running AP and processing the blast FBX files
=> Blast Gem - Fix python script connect order

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
It was discovered that the error log from xacro is cut off on the first angle bracket, making it impossible to see the actual error problem fully if it occurs.
This change surrounds the error text with a code macro (three backticks) so that it shows up in markdown as the actual literal code, which causes Qt to ignore any angle brackets and other markdown inside the text.
Note that this was discovered during fixing 
https://github.com/o3de/o3de-extras/issues/118
but does not fix 118, only makes it better display when errors occur.
How it looks with these changes
=> As part of fixing https://github.com/o3de/o3de-extras/issues/118

Gems/ROS2/Code/Source/Clock/SimulationClock.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
<AzCore/std/sort.h> header was missing in the SimulationClock.
=> added missing sort header

Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp, Gems/ROS2/Code/Tests/UrdfParserTest.cpp
AMENT_PREFIX_PATH contains installed packages. URDF can refer to it as :
`package://example_package`. This change would provide a way to parse it correctly.
As alternative this API can be used: [https://github.com/ament/ament_index/blob/d9f7f2783dedc5687a5bdaf3ce5252dce5c073c5[…]dex_cpp/include/ament_index_cpp/get_package_share_directory.hpp](https://github.com/ament/ament_index/blob/d9f7f2783dedc5687a5bdaf3ce5252dce5c073c5/ament_index_cpp/include/ament_index_cpp/get_package_share_directory.hpp#L25-L33)
I decided to parse AMENT_PREFIX_PATH directly - ament_index_cpp uses exceptions.
Solves #225 
Tested using attached unit tests.
=> ROS2 URDF importer will parse AMENT_PREFIX_PATH

Gems/ROS2/Code/Include/ROS2/Camera/CameraPostProcessingRequestBus.h, Gems/ROS2/Code/Source/Camera/CameraSensor.cpp, Gems/ROS2/Code/Source/Camera/CameraSensor.h, Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.cpp, Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.h, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.h, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.h, Gems/ROS2/Code/ros2_files.cmake, Gems/ROS2/Code/ros2_header_files.cmake
Small refactoring of camera sensor code needed to add post processing, which is very useful for simulation.
Includes exposing the interface to add custom post processing function to the pipeline before publishing data, both for depth and color.
=> Camera sensor post processing abstraction

Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.h
=> ROS2 Lidar Sensor - fix for incorrect calculation of ray's rotation

Gems/ROS2/Code/Source/RobotImporter/Pages/IntroPage.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
I've added a check for an open level while importing a URDF file. If a level is not open this check will prevent further pages in Robot Importer Widget, displaying a message box describing the error. This fixes #265.
=> Add check for open level

Gems/ROS2/Code/Include/ROS2/Camera/CameraPostProcessingRequestBus.h
Improve Post Processing Bus by allowing parallel lockless execution of BusInterface.
Based on [o3de documentation](https://development--o3deorg.netlify.app/docs/user-guide/programming/messaging/ebus-design/#lockless-dispatches)
This fix allows for calling ApplyPostProcessing from multiple threads before previous thread finishes execution.
As of current implementation if post processing is complex enough it creates backlog of threads which want to post-process an image frame.
=> Improve Post Processing Bus 

Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.h
I've changed the signal from textChanged to editingFinished. This fixes issue #284. I've also added a check if the path provided points to a file, not a directory.
=> URDF, modify inputbox signals and handling

Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp
I've added a undo batch for URDF prefab creation, allowing complete undo and redo of imported URDF. This fixes #264. Unfortunately while undoing or redoing there are multiple errors: "[Error] (Prefab) - Failed to find an owning instance for entity with id <id here>". This seems to be related to issues: https://github.com/o3de/o3de/issues/15087, https://github.com/o3de/o3de/issues/15606. These errors also appear without the implemented undo batch, but only while redoing.
=> Create undo batch for prefab maker

Gems/ROS2/README.md
I've removed the redundant documentation from this readme and added a link for the new documentation location.
=> Reference the new location for documentation

Gems/ROS2/gem.json
This change updates the Gem metadata to support versioning: https://github.com/o3de/sig-core/issues/44
Additionaly, it updates the json to include supported platform (Linux).
=> Updated gem.json to reflect versioning RFC

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/xacro/XacroUtils.cpp, Gems/ROS2/Code/Tests/UrdfParserTest.cpp
The PR fix case explained in #307, caused by lack of safety in parsing XACRO file for parameters.
Fixed and tested against manual test cases in :
https://github.com/RobotecAI/o3de-ros2-gem-testing/tree/main/URDFTest
=> Added sanity checks to xacro preventing crash to URDF importer

Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.cpp
I've added a requirement in ROS2WheelOdometry for PhysicsRigidBodyService. This addresses #309.
=> Add requirement for PhysicsRigidBodyService in ROS2WheelOdometry

Gems/ROS2/Code/Source/VehicleDynamics/ManualControlEventHandler.h
Robot manual steering with input handlers is used to give jerky movement. It is no more!
=> Implement all virtual functions from InputEventNotificationBus

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/checkROS2Distribution.cmake
I've modified CMakeLists.txt to check if the initial configuration was run under the same ROS 2 distribution as the one sourced during project setup and build. I've changed CMakeLists.txt such that the ROS 2 distribution will be cached into CMakeCache.txt during the project's configuration. A check during the configuration process prevents users from building when their sourced distribution is different. I've also added the same check during the build process.
Removing the CMakeCache.txt, as proposed by me (```Remove CMakeCache.txt and reconfigure project.```), does not cause rebuilding of the O3DE Engine.
This addresses #135.
=> Add check for ROS2 distribution in CMakeLists.txt

Gems/ROS2/Code/Source/Odometry/ROS2OdometryCovariance.cpp, Gems/ROS2/Code/Source/Odometry/ROS2OdometryCovariance.h, Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.cpp, Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.h, Gems/ROS2/Code/ros2_files.cmake
Allows for changing covariance values in ros2 message.
Limits choice to diagonal for simplicity.
=> ROS2WheelOdometrySensor covariance settings in Editor  

Gems/ROS2/Code/Include/ROS2/Camera/CameraPostProcessingRequestBus.h
It was found that using LocklessDispatch allows for processing multiple frames independently but provides no guarantees while disconnecting. 
Current Implementation sometimes results in asserts on simulation stop if post processing takes significant amount of time.
=> More resilient async ros2 image post processing

Gems/ROS2/Code/Include/ROS2/Manipulation/JointsTrajectoryRequests.h, Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.cpp, Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.h, Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.h
I've implemented a fix for the crash when the moveit action stop was called. The fix requires a separate thread that sets the state of the action server after the cancel request was accepted. This is needed because the state of the action server can be changed to ```canceled``` only after the state is ```canceling```.
There was also another error that would stop moving the joints after a cancelation. This resulted in the joints not keeping their positions and the robot arm to slowly falling with gravity. This was also fixed.
This PR addresses #366
=> Fix crash after moveit action stop

Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_blue.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_corner.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_end1.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_end2.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_line.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_mid1.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/markings_mid2.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/tire_traces1.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Floor_markings/tire_traces_circle.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Materials/MWarehouseStorageOnWheels.material, Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseBoxes/WarehouseBoxesNormal.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseFloor/WarehouseFloorNormal.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseGate/WarehouseGateNormal.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseModules/WarehouseModulesNormal.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseProps/WarehousePropsNormal.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseStorage/WarehouseStorageNormal.png.assetinfo, Gems/WarehouseAssets/Assets/assets/Warehouse/Textures/WarehouseStorageOnWheels/WarehouseStorageOnWheelsNormal.png.assetinfo
Some of the normal textures haven't been configured as normal maps. This caused artifacts. Fixed also decal textures.
Results (before/after):
=> Warehouse Gem:  Fixed normal and decal textures

Gems/ROS2/Code/Include/ROS2/Sensor/SensorConfiguration.h, Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.cpp, Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.h, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.cpp, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h, Gems/ROS2/Code/Source/Sensor/SensorConfiguration.cpp
I've added limits for suitable configuration fields inside sensors. Most of them are minimum limits to eliminate values such as negative frequency. This addresses issue #129.
=> Validate configuration fields for sensors

Gems/ProteusRobot/gem.json, Gems/ROS2/gem.json, Gems/RosRobotSample/gem.json, Gems/WarehouseAssets/gem.json, Gems/WarehouseSample/gem.json, Templates/Ros2FleetRobotTemplate/Template/Gem/gem.json, Templates/Ros2ProjectTemplate/Template/Gem/gem.json
Update compatible_engines fields:
- we will continue to support working with development branch of o3de (so it is >= BASE_VERSION)
- we will not support earlier versions of engine / sdk (there are version tags for that).
=> Update to gem.json files to denote compatible engines

Gems/ROS2/Code/Include/ROS2/Manipulation/JointsTrajectoryRequests.h, Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.cpp, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.h
Invalid goals are now accepted, and later aborted with error message explaining the reason.  Addresses #375.
=> Error messages in Joint Trajectory

Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.h
Added Uuid of parameters passed to XACRO to the name name of RobotImporter's output directory.
This makes the directory unique for each robot imported from the same xacro file. 
Addresses  https://github.com/o3de/o3de-extras/issues/392.
=> Make output directories of RobotImporter unique

Gems/ROS2/Code/Source/Manipulation/Controllers/JointsArticulationControllerComponent.cpp, Gems/ROS2/Code/Source/Manipulation/Controllers/JointsArticulationControllerComponent.h
Added ArticulationLinkService to list of services required by JointsArticulationController.
Relies on https://github.com/o3de/o3de/pull/16321 which introduces ArticulationLinkService to list of services provided by ArticulationLinkComponent and EditorArticulationLinkComponent.
Addresses #389.
=> JointsArticulationController requires ArticulationLink

Templates/Ros2ProjectTemplate/Docker/Dockerfile, Templates/Ros2ProjectTemplate/Docker/LaunchNavStack.bash, Templates/Ros2ProjectTemplate/Docker/LaunchSimulation.bash, Templates/Ros2ProjectTemplate/Docker/README.md, Templates/Ros2ProjectTemplate/Docker/cleanup.bash
This PR implements the last point in the #246 issue. Please double check if #246 can be closed.
The _Dockerfile_ and the remaining files are based on the https://github.com/o3de/RobotVacuumSample docker configuration.
Open questions:
- Docker folder location: on top of the repo or inside of the template folder?
-> if the option to keep this folder top of the repo is selected, an argument to switch between _Ros2FleetRobotTemplate_ and _Ros2ProjectTemplate_ should be added
- is Ubuntu 22.04 with _iron_ a valid choice as default?
-> the target for this PR is `development` branch; I believe _iron_ should be the target for the next stable release
- which o3de and o3de-extras branches should be used? I did use the last stable release, i.e., 2305.0
=> docker environment for Ros2ProjectTemplate

Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp
Added copying of m_resultFlags and m_minRange to move constructor of LidarRaycaster.
This addresses https://github.com/o3de/o3de-extras/issues/401, as previously configuration was lost by this constructor.
This caused RaycastResultFlags::Ranges to be disabled (default value). As a result m_ranges field of RaycastResult was not populated by LidarRaycaster that was moved.
m_minRange was lost in similar manner (this is not connected to issue linked above).
=> added missing fields to move constructor of LidarRaycaster

Gems/ROS2/Code/Include/ROS2/ProximitySensor/ProximitySensorNotificationBus.h, Gems/ROS2/Code/Include/ROS2/ProximitySensor/ProximitySensorNotificationBusHandler.h, Gems/ROS2/Code/Source/Manipulation/MotorizedJoints/PidMotorControllerComponent.cpp, Gems/ROS2/Code/Source/ProximitySensor/ROS2ProximitySensor.cpp, Gems/ROS2/Code/ros2_header_files.cmake
This PR adds _notification bus_ to `ROS2ProximitySensor` (alongside with _ScriptCanvas_ support) and adds _ScriptCanvas_ support to `PidMotorControllerComponent`.
Thanks to that it is possible to use a simple script:
in order to create a more advanced conveyor bus handling (note: the conveyor bus PR is an ongoing work):
[20230707_conveyor_scripts_short.webm](https://github.com/o3de/o3de-extras/assets/134940295/0f6d0655-e160-46f8-8b4f-865b63fc30bb)
=> Support for PID and Proximity sensor buses

Gems/ROS2/Code/Source/ROS2EditorSystemComponent.cpp, Gems/ROS2/Code/Source/ROS2SystemComponent.cpp, Gems/ROS2/Code/Source/ROS2SystemComponent.h
I've added a separate function that initializes the ```LoadPassTemplateMappings```. This fixes #415. There is also a check added for the application type to differently run the initialization function depending if the Game Launcher is used or the Editor.
=> Add pass template mapping handler initialization

Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
This PR addresses the https://github.com/o3de/o3de-extras/issues/395 issue.
~~This PR is WIP.~~
~~It waits 10 seconds for the assets to be processed.~~
~~The PR in the current state can be used if the above bug is encountered.~~
~~The URDF importer was modified to disable watching assets (this breaks the visuals on resolved meshes page).~~
~~To properly import the URDF after the resolved meshes page is shown for the first time we need to use the back button and then the next button. After that, the meshes should be resolved properrly.~~
=> URDFImporter: Wait for meshes to process

Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp
Resolves https://github.com/o3de/o3de-extras/issues/407
=> Added support in JointsManipulationComponent for classic prismatic joints

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Include/ROS2/FactorySimulation/ConveyorBeltRequestBus.h, Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponent.cpp, Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponent.h, Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponentConfiguration.cpp, Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponentConfiguration.h, Gems/ROS2/Code/Source/ROS2ModuleInterface.h, Gems/ROS2/Code/ros2_files.cmake
=> Conveyor belt component.

Templates/Ros2ProjectTemplate/Template/Levels/DemoLevel/DemoLevel.prefab
Fixes: #425 
The problem was with the 31st patch replace operation in _ROSBot_slamtec.prefab_, because of an invalid argument value.
Deleting the patch solved the problem.
=> Fix warnings related to json replace while opening

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/CollidersMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/PrefabMakerUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/PrefabMakerUtils.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.h, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.h, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilder.cpp, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilder.h
This PR modifies the SDFAssetBuilder to produce functional procedural prefabs for URDF model files. It works by calling into the RobotImporter code and saving the result as a procedural prefab in the Cache directory instead of a regular prefab in a source asset directory. 
Features:
* Parses the URDF and generates the procprefab using the same logic as the RobotImporter.
* Creates AP job dependencies on every referenced asset to guarantee the procprefab can be generated and used without race conditions.
To make the code shareable between the Editor RobotImporter and the Asset Builder, some pieces of functionality needed to be refactored slightly, since the Asset Builder has less services available to it. In particular, the code now generates the hierarchy of entities _before_ creating the …
=> [URDF] Functioning asset builder

Gems/ROS2/Code/Source/Communication/TopicConfiguration.cpp
=> Change the message type field in the ROS2 Sensor to read-only.

Gems/ROS2/Code/Source/ContactSensor/ROS2ContactSensorComponent.cpp, Gems/ROS2/Code/Source/ContactSensor/ROS2ContactSensorComponent.h, Gems/ROS2/Code/Source/ROS2ModuleInterface.h, Gems/ROS2/Code/ros2_files.cmake
=> Implement contact sensor component.

Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.cpp, Gems/ROS2/Code/Source/Camera/CameraSensorConfiguration.h, Gems/ROS2/Code/Source/Camera/CameraSensorDescription.cpp
=> Add near and far clipping distance to ROS2 Camera sensor.

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
https://github.com/o3de/o3de-extras/pull/394 resolved https://github.com/o3de/o3de-extras/issues/392 by introducing `dirSuffix` - additional directory path part, that was added in order to make it unique. 
In https://github.com/o3de/o3de-extras/pull/394 `dirSuffix` is an  `AZStd::string_view` created from `paramsUuid.ToString<AZStd::string_view>()`, which is an error, as the string is a temporary value. 
This PR changes it to be a `AZStd::string` instead, so that it's value lives for the duration of call to `CopyAssetForURDFAndCreateAssetMap`.
=> Fixed directory name creation in URDF Importer

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Platform/Linux/PAL_linux.cmake
An `ly_associate_package` call has been added to allow the sdformat13 3rdParty library to be downloaded during CMake configure when building on Linux.
Both a x86_64 and Aarch64 package has been built.
NOTE: These packages have not been uploaded to the O3DE 3rdParty package repo and therefore this change cannot go in until then.
It is posted for review to streamline the process when the package is approved to be uploaded.
=> Adding the sdformat13 3rdParty library as a dependency the `ROS2.Editor.Static` TARGET

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Include/ROS2/RobotImporter/SDFormatSensorImporterHook.h, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.h, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SensorHooks.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SensorHooks.h, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Tests/SdfParserTest.cpp, Gems/ROS2/Code/ros2_editor_api_files.cmake, Gems/ROS2/Code/ros2_editor_files.cmake, Gems/ROS2/Code/ros2_editor_tests_files.cmake, Gems/ROS2/Code/ros2_header_files.cmake
This PR is based on #437
The context: the reflection hook for user-defined mappings will allow developers to add new plugins and support them with gems and components. This will work similarly to AssetBuilder registration system, using SerializeContext reflection system. 
This PR adds the following:
* Add _SDFormat_ sensor importer hook template
* Add sample implementation of the hook for `ROS2CameraSensorEditorComponent`
* Add _SDFormat_ sensor importer hook utilities
* Add tests
=> add SDFormat sensor importer hooks

Gems/ROS2/Code/Include/ROS2/Sensor/ROS2SensorComponent.h, Gems/ROS2/Code/Include/ROS2/Sensor/SensorConfiguration.h, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.h, Gems/ROS2/Code/Source/GNSS/GNSSSensorConfiguration.cpp, Gems/ROS2/Code/Source/GNSS/GNSSSensorConfiguration.h, Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.cpp, Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.h, Gems/ROS2/Code/Source/Imu/ImuSensorConfiguration.cpp, Gems/ROS2/Code/Source/Imu/ImuSensorConfiguration.h, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.cpp, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h, Gems/ROS2/Code/Source/Lidar/Lidar2DSensorConfiguration.cpp, Gems/ROS2/Code/Source/Lidar/Lidar2DSensorConfiguration.h, Gems/ROS2/Code/Source/Lidar/LidarSensorConfiguration.cpp, Gems/ROS2/Code/Source/Lidar/LidarSensorConfiguration.h, Gems/ROS2/Code/Source/Lidar/LidarTemplate.h, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.h, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h, Gems/ROS2/Code/Source/ProximitySensor/ROS2ProximitySensor.cpp, Gems/ROS2/Code/Source/ProximitySensor/ROS2ProximitySensor.h, Gems/ROS2/Code/Source/Sensor/ROS2SensorComponent.cpp, Gems/ROS2/Code/Source/Sensor/SensorConfiguration.cpp, Gems/ROS2/Code/ros2_files.cmake, Gems/RosRobotSample/Assets/ROSBot_slamtec.prefab, Gems/RosRobotSample/Assets/ROSbot_velodyne.prefab
* move configuration of `ROS2GNSSSensorComponent`, `ROS2ImuSensorComponent`, `ROS2LidarSensorComponent`, and `ROS2Lidar2DSensorComponent` to separate structs
* add constructors for _ROS2SensorComponents_ that take parameters
The goal of this PR is to simplify the implementation of methods for creating sensors (it will be used in _RobotImporter_).
=> Constructors with parameters in ROS2SensorComponents

Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilder.cpp, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilder.h, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilderSettings.cpp, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilderSettings.h, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilderSystemComponent.cpp, Gems/ROS2/Code/ros2_editor_files.cmake, Gems/ROS2/Registry/assetprocessor_settings.setreg, Gems/ROS2/Registry/sceneassetimporter.setreg, Gems/ROS2/Registry/sdfassetbuilder_settings.setreg
This PR changes the SdfAssetBuilder to read in global builder settings from a setreg file to apply as the defaults when building all assets. Changes to the settings in the setreg file will cause all affected assets to rebuild the next time the AP is run. Currently, the only global setting that exists is "UseArticulations", but other settings can be added easily.
The mechanism used for rebuilding the assets is the builder "fingerprint". Any time the fingerprint changes, the builder will rebuild all of its assets. The global settings are read in from the setreg file and then serialized back out into a JSON string that is used as the fingerprint. Changes to the settings changes the fingerprint string, which triggers the rebuild.
This PR also has a separate change to the ROS2 Gem to enable …
=> Add the concept of global settings to the SdfAssetBuilder

Gems/ROS2/Code/Source/FactorySimulation/ConveyorBeltComponent.cpp
`ConveyorBeltComponent` serialization did not take into consideration the base class, which should also be serialized. There was the information about it in O3DE console:
Now it is gone.
=> fix ConveyorBeltComponent serialization

Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
Addresses https://github.com/o3de/o3de-extras/issues/441.
Changes based on the visualization code in EditorCameraComponent.
=> Frustrum of ROS2CameraSensorComponent visualized correctly.

Gems/ROS2/Code/Include/ROS2/Sensor/ROS2SensorComponent.h, Gems/ROS2/Code/Include/ROS2/Utilities/PhysicsCallbackHandler.h, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.cpp, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h, Gems/ROS2/Code/Source/Manipulation/JointStatePublisher.cpp, Gems/ROS2/Code/Source/Manipulation/JointStatePublisher.h, Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.h, Gems/ROS2/Code/Source/Manipulation/ManipulationUtils.cpp, Gems/ROS2/Code/Source/Manipulation/ManipulationUtils.h, Gems/ROS2/Code/Source/Odometry/ROS2OdometrySensorComponent.cpp, Gems/ROS2/Code/Source/Odometry/ROS2OdometrySensorComponent.h, Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.cpp, Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.h, Gems/ROS2/Code/Source/Utilities/ArticulationsUtilities.cpp, Gems/ROS2/Code/Source/Utilities/ArticulationsUtilities.h, Gems/ROS2/Code/Source/Utilities/PhysicsCallbackHandler.cpp, Gems/ROS2/Code/Source/Utilities/PhysicsCallbackHandler.h, Gems/ROS2/Code/ros2_files.cmake, Gems/ROS2/Code/ros2_header_files.cmake
Solves issue https://github.com/o3de/o3de-extras/issues/410
The solution uses one bus request per joint. This has a performance impact, but it's fairly small for publishers with a reasonable number of joints (for 9 joints about 90% of the performance impact is caused by the ros2 publishing itself). The performance can be further improved by using JointHandles and SimulatedBodyHandles instead of buses, but the code for it got so hideous I gave up on it and decided that this is the better solution after all.
=> Increase max publishing frequency of joint_states messages

Gems/ROS2/Code/Include/ROS2/Frame/NamespaceConfiguration.h, Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameComponent.h, Gems/ROS2/Code/Source/Frame/NamespaceConfiguration.cpp, Gems/ROS2/Code/Source/Frame/ROS2FrameComponent.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.h
Support for namespace parameter in the robot spawner.
=> Spawning with namespace

Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
Game Launcher does not reflect Editor Components, this means that `CameraSensorConfiguration` was not reflected in Game Launcher at all.
This PR fixes this problem.
=> Fix Camera Sensor Reflection to work in GameLauncher

Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.h, Gems/ROS2/Code/Source/RobotImporter/Pages/PrefabMakerPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/PrefabMakerPage.h, Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.h, Gems/ROS2/Code/Source/RobotImporter/xacro/XacroUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/xacro/XacroUtils.h, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilder.cpp, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilderSettings.cpp, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilderSettings.h, Gems/ROS2/Code/Tests/UrdfParserTest.cpp
An `SDFAssetBuilderSettings` object is being exposed via the File Select page in the Robot Importer to allow users to alter the preserve URDF fixed joints object. The settings are sourced from their current values within the Settings Registry.
Refactored the `UrdfParser::Parse` functions to support capturing the sdf::Console messages logged during URDF/SDF parsing.
=> Adding SDFAssetBuilderSettings Reflected Property Editor to the Robot Importer

Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.h
Revert #400 using old better logic.
The #400 was used to circle navigate issue in asset processor. 
Also missing case for resolving package was added.
=> Reverted PR #400, fixes to URDF importer

Templates/Ros2RoboticManipulationTemplate/README.md, Templates/Ros2RoboticManipulationTemplate/Template/Examples/panda_moveit_config_demo.launch.py, Templates/Ros2RoboticManipulationTemplate/Template/Gem/enabled_gems.cmake, Templates/Ros2RoboticManipulationTemplate/Template/project.json
=> Fixes to ROS2RoboticManipulationTemplate

Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.h, Gems/ROS2/gem.json
Fix #478 
PrimitiveAssets Gem is used to visualize primitives. The change was tested on [simple URDF](https://github.com/RobotecAI/o3de-ros2-gem-testing/blob/main/URDFTest/02_IMPORTING_VALID_SIMPLE_URDF/IMPORTING_VALID_SIMPLE_URDF_TESTCASE.md) containing all four types of visuals.
=> use PrimitiveAssets Gem to visualize primitives

Gems/WarehouseAutomation/Code/Source/ConveyorBelt/ConveyorBeltComponent.cpp
If the speed of the ConveyorBeltComponent was set to a negative value, belt segments were massively spawned in an infinite loop, causing a crash eventually. The belt was not moving correctly.
Setting a negative speed is the simplest way of changing movement direction.
Moved from https://github.com/RobotecAI/o3de-extras/pull/35
=> ConveyorBeltComponent: fix for negative value of speed

Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.h
Namespaces are required to support communication with multiple robots.
=> Mainpulation Components - add support for initial positions namespaces.

Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.cpp, Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.h, Gems/ROS2/Code/Source/RobotImporter/Pages/CheckUrdfPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/CheckUrdfPage.h, Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.h, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilder.cpp, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilderSettings.cpp, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilderSettings.h, Gems/ROS2/Code/ros2_editor_files.cmake, Gems/ROS2/Registry/sdfassetbuilder_settings.setreg
Some proposition to solve #476  and #472.
=> Try to fix urdfs in memory before SDF import

Gems/ROS2/Code/Source/RobotImporter/URDF/CollidersMaker.cpp
Fixes https://github.com/o3de/o3de-extras/issues/504.
on the left: before this change, collider is not scaled.
on the right: after change, the scale is applied correctly
Collider has the scale set:
=> Robot Importer: set scale of colliders during import

Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/CheckUrdfPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/FileSelectionPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/IntroPage.cpp, Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.h, Gems/ROS2/Code/Source/RobotImporter/URDF/ArticulationsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/ArticulationsMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/CollidersMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/CollidersMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/InertialsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/InertialsMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/JointsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/JointsMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/PrefabMakerUtils.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.h, Gems/ROS2/Code/Source/RobotImporter/Utils/FilePath.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/FilePath.h, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Source/SdfAssetBuilder/SdfAssetBuilder.cpp, Gems/ROS2/Code/Tests/SdfParserTest.cpp
UI references to "URDF" have been updated to mention "URDF/SDF"
Added additional UnitTest to validate loading SDF files
Added a VisitModels utility function that can visit all models within an SDF
Updated the GetMeshesFilename function to support gather mesh data from all models within an SDF including nested models and models from world tags
Updated the URDFPrefabMaker to visit all the models with an SDF instead of only the first model found within the SDF root or the first model found within the first world tag of an SDF.
```
LIB: libROS2.Editor.Tests
Loading: libROS2.Editor.Tests
OKAY Library loaded: libROS2.Editor.Tests
OKAY Symbol found: AzRunUnitTests
[==========] Running 30 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from SdfParserTest …
```
=> Updating the Robot Importer to support importing in .sdf/.world files

Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.cpp, Gems/ROS2/Registry/sdfassetbuilder_settings.setreg
1. Fixes a crash that can occur if you try to create a prefab on a model where one or more assets haven't resolved.
2. Adds "../models" to the standard path resolvers, since I hit several cases in our test repositories that all needed this same resolver.
=> Misc importer fixes

Gems/ROS2/Code/Source/Lidar/LidarRegistrarSystemComponent.cpp, Gems/ROS2/Code/Source/Lidar/LidarSensorConfiguration.cpp, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.h, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h
This PR fixes an issue that was introduced in #482.
There was an extra call to the non-existent `LidarRegistrarSystemComponent` from a simple configuration structure. When Asset Builder tried to run parse prefab (in serialize context) but ended up dereferencing non-existent pointer to System Component.
The call is `Details::GetDefaultLidarSystem()` in the constructor `LidarSensorConfiguration::LidarSensorConfiguration`, because setting up the default Lidar system is done in EditContext of the respective component.
I also added some assertions and missing required services.
=> Resolve failing asset builder jobs for ROS2 components.

Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
Fixes https://github.com/o3de/o3de-extras/issues/514. Performs deduplication of filenames of assets by counting occurences of each filename and adding prefix to it if needed. 
With this change fanuc is imported correctly:
=> Robot Importer: Renaming duplicated asset filenames.

Gems/ROS2/Code/Source/Gripper/VacuumGripperComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp, Gems/WarehouseAutomation/Code/Source/ConveyorBelt/ConveyorBeltComponent.cpp, Templates/Ros2ProjectTemplate/Template/Gem/CMakeLists.txt, Templates/Ros2ProjectTemplate/Template/Gem/enabled_gems.cmake
This applies suggestion from https://github.com/o3de/o3de-extras/issues/493.
~~There are linker issues still present after those changes.~~
The linker issues were caused by dependency on AWSCore Gem, that is now removed.
=> Ros2ProjectTemplate fixes to monolithic build

Gems/WarehouseAutomation/Code/Source/ConveyorBelt/ConveyorBeltComponent.cpp
This assertion was triggered during initialization causing spurious warnings and made debugging experience hard.
=> Remove assertion that caused problem with debugging

Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.cpp
This fixes compilation error, as there is a conversion from `AZStd::string` to `std::string` that cannot happen automatically.
=> Fixed compilation in UrdfFix

repo.json
The repo.json gem compatibility does not match what is in the actual ROS2 gem.json causing the ROS2 gem to fail compatibility checks before downloading in Project Manager. 
*Testing*
I am not currently setup to test this on Linux, but at the very least this non-code change shouldn't break things any worse than before.
=> Fix ROS2 remote gem compatibility

Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.cpp, Gems/ROS2/Code/Source/RobotImporter/FixURDF/FixURDF.h, Gems/ROS2/Code/Source/RobotImporter/FixURDF/URDFModifications.h, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.h, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.h, Gems/ROS2/Code/Source/RobotImporter/xacro/XacroUtils.cpp
Proposition of a way to present modifications of URDF to user:
Resolves https://github.com/o3de/o3de-extras/issues/512.
Note: this PR includes commits from https://github.com/o3de/o3de-extras/pull/511, and should be merged after it.
=> display explanations of modifications made to URDF

Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
OBJ files such as the tm12-arm1 can have thousands of submeshes due to the way OBJ files are processed by AssImp. This PR changes the Robot Importer to turn on AssImp optimization settings for OBJ files only to collapse redundant submeshes down to the most optimal set.
This PR relies on the companion O3DE PR to introduce the concept of import settings:
https://github.com/o3de/o3de/pull/16753
These changes produce a tm12-arm1.obj.assetinfo file that looks like the following:
```
{
"values": [
{
"$type": "{41DCBEAB-203C-4A05-96FA-98E1D8A96FA1} ImportGroup",
"ImportSettings": {
"OptimizeScene": true,
"OptimizeMeshes": true
}
},
{
"$type": "{07B356B7-3635-40B5-878A-FAC4EFD5AD86} MeshGroup",
"name": "tm12-arm1",
"nodeSelectionList": {
"selectedNodes": [
"$MergedNode_0", …
```
=> Add import optimization settings for obj files.

repo.json
This change merges the fix for the ROS2 gem version compatibility from `stabilization/2310` to `development`.
=> Merge repo.json fix for ROS2 gem version

Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.h, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Tests/SdfParserTest.cpp, Gems/ROS2/Code/Tests/UrdfParserTest.cpp
Link names within an SDF are only unique with a <model> tag, not unique across the entire SDF document.
The `CreatePrefabTemplateFromUrdfOrSdf` function has been modified to create a JointMapper object which stores a mapping of joints to all their parent and child links. It also creates a mapping of joints to the model they are directly attached to.
A similar LinkMapper structure has been added for SDF links, which stores a mapping of the link to their attached model.
Instead of `CreatePrefabTemplateFromUrdfOrSdf` creating a mapping of SDF link name to O3DE Entity, that mapping has now been updated toi map the SDF link pointer to O3DE Entity. This ensures that SDF links with same name are not lost when mapping to O3DE entities. This is needed as SDF links and joints are only required to …
=> Updated the URDFPrefabMaker to avoid referencing SDF link names 

Gems/ROS2/gem.json, repo.json
This updates the `gem.json`, the `repo.json` and provides the download URL for the .zip containing the gem with the SHA256.
The generated .zip archive for ROS2 version 2.0.0 has been uploaded to the [2.0 release](https://github.com/o3de/o3de-extras/releases/tag/2.0)
These changes were made using the o3de CLI like so:
```bash
f:/o3de/scripts/o3de.bat edit-repo-properties --repo-path f:/git/o3de-extras/repo.json --add-gem f:/downloads/ros2-1.0.0 --release-archive-path f:\git\o3de-extras\build --download-prefix https://github.com/o3de/o3de-extras/releases/download/2.0
f:/o3de/scripts/o3de.bat edit-repo-properties --repo-path f:/git/o3de-extras/repo.json --add-gem f:\git\o3de-extras\Gems\ROS2 --release-archive-path f:\git\o3de-extras\build --download-prefix …
```
=> Update ROS2 gem.json on repo.json compatible versions to o3de>=2.1.0

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
The `RobotImporterWidget::CreatePrefab` function had its call to `CheckCyclicalDependency` removed as part of a conflict when resolving a rebase operations.
This change adds back the line that was removed in commit https://github.com/o3de/o3de-extras/commit/6acba55cc034d869a48ee590e7062cf18b3a8fc1#diff-a94c8f5626d21f747b96f4077dd8eb2119c48048840f5db593071a7a96c5a577
=> Adding back inadvertent code deletion from the RobotImporterWidget.cpp

repo.json
We need update the ROS2 gem based on the stabilization branch since it is different than the development branch
=> Update the ROS2 gem zip for stabilization

Gems/ROS2/Code/Platform/Linux/PAL_linux.cmake
The new revision of libsdformat comes with debug symbols, that can be used to get symbol information when debugging the RobotImporter using lldb/gdb
=> Updating ROS2 Gem to use libsdformat-13.5.0-rev2

Gems/ROS2/Assets/seedList.seed
This PR introduces default seedList to `ROS2 Gem` containing `rospasstemplates.azasset`.
Launching standalone GameLauncher without this asset results in segfault if any ROS2CameraSensorComponent is present in the scene
Default seedList is included by default if ROS2 Gem is enabled according to [documentation](https://development--o3deorg.netlify.app/docs/user-guide/programming/gems/creating/)
This change does not influence `ROS2 Gem` functionality
=> Create default seedList with required .pass Asset

Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2CameraSensorHook.cpp
The field of view of the newly created camera was stored in radians instead of degrees. Now it works as expected.
Tested with Robotis OP3 robot.
=> sensor importer: fix camera fov

Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.h, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h
Added a `GetModelContainingModel` function that can return the parent model of a nested model
Updated the URDFPrefabMaker to create an Entity for which represents the URDF/SDF model itself.
The AddEntitiesForLink function has been updated to to pass in the model that the link is attached to and in order to allow the CollidersMaker, ArticulationsMaker and SensorsMaker have access to the Model
Updated the Check Asset Page to not add Assets with empty source paths or null Asset IDs to the list of resolved assets
=> SDF Nested Model Support Changes

Templates/Ros2FleetRobotTemplate/Template/Prefabs/ProteusLaserScanner.prefab, Templates/Ros2FleetRobotTemplate/Template/Registry/physxsystemconfiguration.setreg
After changes to lidar reflection (LidarCore introduction) Proteus prefab changes did not follow up. Moreover, lidar ignore layer handling was updated. For these two reasons, ROS2 Fleet Template did not work - lidar rays were being reflected from robot internal surfaces, making robots impossible to navigate.
This request updates ProteusLaserScanner prefab and configures lidar ignore layers.
This request solves #557.
=> Fix not working lidars in ros2 fleet template

Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Tests/SdfParserTest.cpp
The UnitTest also verifies the URI Prefixes are resolved by libsdformat real files.
depends on o3de/o3de#16859
Updated URDFPrefabMaker to also add the parent model entities for the nested model entities.
The parent model entities of the nested models actually contains the pose information needed to translate and rotate the nested model into the correct location.
=> Adding UnitTest for verifying import of nested SDF import via the `<include>` tag

Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp
A block of code got merged out by mistake on a recent checkin, causing the ROS2 Gem to no longer compile.
=> Restore code that got merged out by mistake.

Gems/ROS2/Code/Source/RobotImporter/URDF/PrefabMakerUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/PrefabMakerUtils.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Tests/UrdfParserTest.cpp
The pose information from the SDF is a value relative to it's attached frame. The `GetLocalTransfromURDF` function was misnamed and returning the a local transform for any SDF link supplied to the function.
Also the `PrefabMakerUtils::SetEntityParent` function which is used to attach a child entity to a parent entity, preserves the world transform of the child entity. Therefore any pose information on child entities such as nested models or links on a model would be set in world space and not in local space.
Verified that the nested model entities and link entities were transformed relative to the parent model entity
=> Fixed parenting of SDF model and link entity transforms

Gems/ROS2/Code/Include/ROS2/ROS2Bus.h, Gems/ROS2/Code/Source/ROS2SystemComponent.cpp, Gems/ROS2/Code/Source/ROS2SystemComponent.h
This is much more efficient for large number of dynamic frames (multi-robot sims)
=> broadcast transforms en masse

Gems/WarehouseAutomation/Code/Source/WarehouseAutomationModule.cpp, Gems/WarehouseAutomation/gem.json
There was a duplicated _guid_ in two different modules - probably a copy-paste error in the creation:
https://github.com/o3de/o3de-extras/blob/5e2a13b0f3c8b4ce07a82c409b4a70e18e4f47f8/Gems/WarehouseAutomation/Code/Source/WarehouseAutomationEditorModule.cpp#L15
https://github.com/o3de/o3de-extras/blob/5e2a13b0f3c8b4ce07a82c409b4a70e18e4f47f8/Gems/WarehouseAutomation/Code/Source/WarehouseAutomationModule.cpp#L15
=> change duplicated guid in WarehouseAutomation

Gems/ROS2/Code/Source/Lidar/LidarSystem.h, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2LidarSensorHook.cpp
Previously lidar hook in robot importer was adding `ROS2LidarSensorComponent` for all lidar sensors. Now it can also add `ROS2Lidar2DSensorComponent` based on the configuration in URDF input file (number of vertical scan samples). 
It also solves the issue that was quickfixed in #587. 
This PR was tested by importing Husarion Robot with Slamtec and Velodyne Puck lidars.
=> RobotImporter: add Lidar2D and sdf::GPU_LIDAR support

Gems/ROS2/Code/Source/RobotImporter/URDF/PrefabMakerUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/PrefabMakerUtils.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Tests/SdfParserTest.cpp, Gems/ROS2/Code/Tests/UrdfParserTest.cpp
This PR cherry-picks PR #578 and PR #591 into the point-release so that nested model SDF imports work correctly.
Tested by importing aws-robomaker-bookstore in the point-release branch and verifying that it imported correctly.
=> Cherry-pick: Merge pull request #578 and #591 - Nested Model fixes

Gems/ROS2/Code/Include/ROS2/ROS2Bus.h, Gems/ROS2/Code/Source/ROS2SystemComponent.cpp, Gems/ROS2/Code/Source/ROS2SystemComponent.h
This PR allows SystemComponents in Editor to get ros2Node without actively querying ROS2SystemComponent for its state.
Decouples ROS2 SystemComponent state from assumptions based on external events. 
Useful when creating components that publish data originating from other system components.
=> Simple API to listen for ros2 system component state change

Gems/ROS2/Code/Source/RobotImporter/Pages/PrefabMakerPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/PrefabMakerPage.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerEditorComponent.cpp
I've modified the spawning behavior of the Robot Importer to always display the default spawn position as the first one. I've also changed the importer such that robot prefabs are moved and not the first entity during the move.
Resolves #597
=> Change spawnning of robots during import

Gems/RosRobotSample/Assets/ROSBot_slamtec.prefab, Gems/RosRobotSample/Assets/ROSbot_velodyne.prefab
Lidars in `RosRobotSample` gem were set to custom instead of the defined ones. Some parameters were incorrect.
Before:
After:
=> fix lidars in ROSBot prefabs

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.h
Resolves #142.
I've changed the spawn_entity service such that the response after adding the entity to the spawn queue is not imminently sent. Now the completion callback sends the response after spawning the entity.
=> Defer response in spawn entity service

Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkDevice.h, Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkInput.h, Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkSession.h, Gems/OpenXRVk/Code/Include/OpenXRVk/OpenXRVkUtils.h, Gems/OpenXRVk/Code/Source/OpenXRVkDevice.cpp, Gems/OpenXRVk/Code/Source/OpenXRVkInput.cpp, Gems/OpenXRVk/Code/Source/OpenXRVkSession.cpp, Gems/OpenXRVk/Code/Source/OpenXRVkUtils.cpp, Gems/OpenXRVk/Code/Source/XRCameraMovementComponent.cpp, Gems/OpenXRVk/Code/Source/XRCameraMovementComponent.h, Gems/OpenXRVk/gem.json, Gems/XR/Code/Include/XR/XRSession.h, Gems/XR/Code/Include/XR/XRSystem.h, Gems/XR/Code/Source/XRSystem.cpp, Gems/XR/gem.json, Projects/OpenXRTest/project.json
This PR improves XrSpaces location calculation.
Previously, XrSpaces were being located each frame
during OpenXRVkInput::PollActions() which was called
before OpenXRVk::Device::BeginInternal(). The problem
with that approach is that xrLocateSpace needs
a "predicted display time" for the CURRENT frame.
But the "predicted display time" is calculated during
OpenXRVk::Device::BeginInternal(), this means that all XrPoses
for the CURRENT frame were calculated with the "predicted
display time" of the PREVIOUS frame. This was causing the rendered
frames to look jittery.
In this PR, the XrSpaces are now located during
OpenXRVk::Device::BeginInternal() this guarantees that
when xrLocateSpace is called it is using the correct
"predicted display time" for the CURRENT frame. This improves
the jitter …
=> OpenXR Fixes

Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.h
Resolves #607.
I've added a flushIOOfAsset function that flushes the assets to make the copied files available to the Asset Processor before further processing. 
This addition slows down the importing process. After clicking next in the page before CheckAssetsPage the user needs to wait and the window does not reflect that anything is being done in the background (the files are being copied). I've proposed a UX change in #617.
=> FlushIO after copying files in Robot Importer

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.h
I've added a service that allows to despawn a spawned entity.
I've modified the `spawn_entity` service to include the name of the ticket (this will become the name of the robot used to remove it later) in the `status_message`.
By calling the `gazebo_msgs/srv/DeleteEntity` service with the `name` parameter set to the response of the spawn service the entity will be deleted.
Resolves #618
=> Add delete entity service

Gems/ROS2/Code/Source/Georeference/GNSSFormatConversions.h, Gems/ROS2/Code/Tests/GNSSTest.cpp
Changes in namespaces `GNSS` -> `Utils::GeodeticConversions` in #604 caused some errors while building tests, this PR fixes it.
=> Fix GNSSTest after changes in #604

Gems/ROS2/Code/Source/Utilities/Controllers/PidConfiguration.cpp
`P` was not enabled in the editor component
=> Fix for serialization of PID parameters

Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.cpp
Fixes SIGINT & SIGTERM handling to adequately shut down o3de processes that host an rclcpp instance, especially to fix process termination via `CTRL+C` keyboard command
Cf. https://github.com/ros2/rclcpp/issues/317#issuecomment-380318892
=> Fix rclcpp SIGINT & SIGTERM handling

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
Depends on #611.
Resolves #136.
I've added a check before the spawning of the Entity. This checks if the asset was loaded without error and returns a negative response when the error is detected.
Additionally in the o3de/development branch, the new DPE feature shows when a spawnable is improperly loaded.
There is no possibility to input a non spawnable in the above menu as the field is `AZ::Data::Asset<AzFramework::Spawnable>`.
=> Spawnable validation

Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/CheckAssetPage.h, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.h, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/SourceAssetsStorage.h
This PR depends on #616.
Resolves #617.
This PR improves the UX of the robot importer, by creating a separate thread for copying files. 
Usage example:
https://github.com/o3de/o3de-extras/assets/130671280/a53e20f8-ea45-43ef-b721-226621960d84
=> improve ux for robot importer check assets

Gems/ROS2/Code/Source/RobotImporter/Pages/ModifiedURDFWindow.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/ModifiedURDFWindow.h, Gems/ROS2/Code/Source/RobotImporter/Pages/ModifiedUrdfWindow.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/ModifiedUrdfWindow.h, Gems/ROS2/Code/Source/RobotImporter/Pages/PrefabMakerPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/PrefabMakerPage.h, Gems/ROS2/Code/Source/RobotImporter/Pages/RobotDescriptionPage.cpp, Gems/ROS2/Code/Source/RobotImporter/Pages/RobotDescriptionPage.h, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.h, Gems/ROS2/Code/Source/RobotImporter/URDF/ArticulationsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/ArticulationsMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/UrdfParser.cpp, Gems/ROS2/Code/ros2_editor_files.cmake
This PR adds multiple changes to _RobotImporter_ wizard:
1. A bugfix for `Create prefab` button from the last wizard page - the button was never gone when the _back_ button was pressed
2. The page notifying about URDF parsing was redesigned not to include the modified source code anymore - this code can be either displayed in a separate window or saved to the file to use later. This change is caused by the fact that the source code can be long. Moreover, it might happen some other warnings are printed after to code. I believe it is hard to read for the most.
3. The page displaying prefab creating logs was redesigned to print _Markdown_ and the logs were split into categories. This part will be later used to display logs from SDFormat sensor and plugin importer.
I also renamed one file as …
=> Update RobotImporter wizard

Gems/ROS2/Code/Source/Utilities/Controllers/PidConfiguration.cpp
Cherry-pick #635 to 2310.2 point release
The code was built and the `P` parameter is available.
=> Cherry-pick #635 to 2310.2

Gems/ROS2/Code/Include/ROS2/GNSS/GNSSPostProcessingRequestBus.h, Gems/ROS2/Code/Include/ROS2/Sensor/ROS2SensorComponentBase.h, Gems/ROS2/Code/Include/ROS2/Sensor/SensorConfigurationRequestBus.h, Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.cpp, Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.h, Gems/ROS2/Code/Source/ROS2ModuleInterface.h, Gems/ROS2/Code/ros2_header_files.cmake
1. Added GNSS post processing bus
2. Added SensorConfiguration bus 
3. Added API to get/set SensorConfiguration for ROS2SensorComponentBase
4. Minor adjustment
-  Added interface for controlling sensor state on the runtime without disabling enabling sensor.
- Added GNSS post processing API
=> Exposing publishing switch api and adding post processing api for GNSS

Gems/ROS2/Code/Source/RobotControl/Controllers/RigidBodyController/RigidBodyTwistControlComponent.cpp, Gems/ROS2/Code/Source/RobotControl/Controllers/RigidBodyController/RigidBodyTwistControlComponent.h
This PR adjusts the behavior of component `RigidBodyTwistControlComponent`.
This component used to apply twist (linear and angular velocity) every ROS 2 message callback.
It caused two problems:
- robot was not moving smooth
- the speed was affecting the rate of publication of twist message.
Theoretically it should enable possibility to have flying robots (multi copters) basic simulation 
The PR will affect the VacuumDemo (probably in positive way). I will test it and remove draft status.
=> Adjusted Twist component to apply twist in every phycis step.

Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2SkidSteeringModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.h, Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp, Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.h, Gems/ROS2/Code/Source/VehicleDynamics/Utilities.cpp
This PR fixes some issues in _SkidSteeringDriveModel_ implementation. Both the method for applying the rotation to wheels based on the requested model movement and the method for calculating the model's movement based on the wheels' rotation were refactored.
- The track parameter is used instead of the wheelbase parameter for calculation (Closes #615), the naming is also unified and fixed.
- The same distance between wheels is used in the codebase (it was two times bigger while [getting the speed](https://github.com/o3de/o3de-extras/blob/d9fc445a72a30ed683cf6cb18dfa8b3a3e762f6a/Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/SkidSteeringDriveModel.cpp#L60) than while [applying the speed](https://github.com/o3de/o3de-extras/blob/d9fc445a72a30ed683cf6cb18dfa8b3a3e762f6a/Gems/ROS2/Code/Sour …
=> Fix SkidSteeringDriveModel

Gems/ROS2/Code/Include/ROS2/Utilities/Controllers/PidConfiguration.h, Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2AckermannModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2SkidSteeringModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2ModelPluginHooks.h, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.h, Gems/ROS2/Code/Source/Utilities/Controllers/PidConfiguration.cpp, Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/AckermannDriveModel.cpp, Gems/ROS2/Code/Source/VehicleDynamics/DriveModels/AckermannDriveModel.h, Gems/ROS2/Code/Source/VehicleDynamics/ModelComponents/AckermannModelComponent.cpp, Gems/ROS2/Code/Source/VehicleDynamics/ModelComponents/AckermannModelComponent.h, Gems/ROS2/Code/Source/VehicleDynamics/ModelLimits/AckermannModelLimits.cpp, Gems/ROS2/Code/Source/VehicleDynamics/ModelLimits/AckermannModelLimits.h, Gems/ROS2/Code/Source/VehicleDynamics/WheelControllerComponent.cpp, Gems/ROS2/Code/Source/VehicleDynamics/WheelControllerComponent.h, Gems/ROS2/Code/ros2_editor_files.cmake
This PR adds a hook for importing Ackermann plugin from SDFormat data.
This hook was tested using the attached model. When imported with articulations, the only missing part is setting `use motor = true` in steering joints, which is currently impossible due to missing interfaces in articulations (impossible to change any settings). The same setting is set correctly for wheels based on wheel material information. When importer without articulations, all parameters are set accordingly.
[ackermann_nomesh.zip](https://github.com/o3de/o3de-extras/files/13948582/ackermann_nomesh.zip)
The movement of robots is not perfect after the import and all parameters such as motor force and damping, links' weights, etc., should be adjusted manually. But the import works as expected - please use the …
=> RobotImporter: add Ackermann model hook

Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.cpp
In the previous implementation, SDFormat `<sensor>` tag was triggering the import hook based on the sensor type only and it did not use the `<plugin>` information at all. Now, the hook is matched based on both. In particular:
- a default hook is triggered when no `<plugin>` is implemented for a particular sensor
- a specific hook is selected based on the `<plugin>` data if available
This way the user might add their hook with their sensor implementation by using their own plugin name declared in the hook, e.g.  it is possible to add a hook for the popular `libhector_gazebo_ros_imu` plugin.
Tested using three different camera plugins in sdf files, with standard camera plugin:
```xml
<sensor name="camera_test" type="camera">
<plugin name="camera_plugin" filename="libgazebo_ros_camera.so"/> …
```
=> redo SDFormat sensor import condition

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Tests/ROS2EditorTest.cpp
fixes: #656 
By adding necessary hook for running Unit Tests.
After this PR only ros2 python smoke tests are failing.
Building all ros2 gem tests:
```
cmake --build . --config debug --target ROS2.Editor.Tests ROS2.Tests ROS2.Frame.Tests
```
and running 
```
ctest -C debug -R "ROS2" --output-on-failure
```
Introducing failure inside Editor tests correctly shows failing test.
on commits
- o3de - `5ae4e51252`
- o3de-extras - `85cd1399`
=> Add AzRunUnitTests Hook to Editor Tests

Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.cpp, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.h, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraConfiguration.cpp, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraConfiguration.h
Following camera allows to switch camera to many different location, but it can tilt (horizon tilts with robot).
With this feature, the rotation matrix is decomposed in such manner that pitch and yaw is removed.
Manual test with internal project.
=> Add feature to prevent camera from tilting

Gems/ROS2/Code/Source/Frame/ROS2FrameConfiguration.cpp
This PR depends on #659.
Fixes #661
This PR changes the edit context for effective namespace in the ROS2FrameEditorComponent. This will prevent the o3de engine form showing the effective namespace as overridden.
The UI changes:
By importing a robot using the robot importer.
=> UI handler for effective namespace

Gems/ROS2/Code/Source/Frame/ROS2FrameEditorComponent.cpp
`ROS2FrameEditorComponent` was not reflecting its base class and, as a result, it was triggering an error message. This is fixed now.
The code was built and the project using `ROS2FrameEditorComponent` loaded with no error messages.
=> fix reflection in ROS2FrameEditorComponent

Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2CameraSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2GNSSSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2ImuSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2LidarSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.h, Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Tests/UrdfParserTest.cpp
SDFormat allows for `<pose>` tag within the sensor tag. This PR modifies the way sensors are created - instead of adding them directly to the hosting links, separate links are created for each sensor (as for visuals) and `<pose>` value is applied to the link.
Robotis OP3 robot was imported with and without `<pose>` tag.
***
This PR is set as a draft, as it is built on top of #632 - waiting for AR to be fixed and #632 to be merged.
=> RobotImporter: Support <pose> within <sensor>

Gems/ROS2/Code/Source/RobotImporter/Pages/RobotDescriptionPage.cpp, Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2LidarSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.h
This PR adds the functionality of printing log messages about created sensors in the RobotImporter wizard. It also lists SDFormat tags that were not parsed correctly:
Additionally:
- buttons to save modified URDF were disabled in cases URDF is not modified
- SDFormat parser logs are also treated as import warnings and displayed in the wizard
- wizard dialog that was intended to be skipped is skipped now (this part of the code was refactored)
- titles/logs sizes were unified
- a warning about too many articulation links (causing segfault) was added in the _PrefabMaker_ window
Multiple different URDF, Xacro and SDFormat models were imported
***
Set to draft: waiting for #632 to be merged
=> RobotImporter: print sensor import log in wizard

Gems/ROS2/Code/Source/Camera/CameraSensor.cpp, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp
Fixes #674.
`AZ::Transform` contains translation, rotation, and scale. When calculating MVP for lidar sensor and camera sensor we only care about translation and rotation, hence the scale should be ignored. 
A robot was scaled up and down, the camera outputs were compared.
=> don't use scale in MVP calculation for sensors

Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2AckermannModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2SkidSteeringModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/RobotControlMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/RobotControlMaker.h, Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp
This PR adds the functionality of printing log messages about created model control plugins in the RobotImporter wizard, as in  #648 for sensors. It also lists SDFormat tags that were not parsed correctly:
SDFormat data with Ackermann and Skid Steering examples were imported.
[sample_models.zip](https://github.com/o3de/o3de-extras/files/14587299/sample_models.zip)
=> RobotImporter: print model control plugins import log in wizard

Templates/Multiplayer/Template/Gem/Code/Source/Spawners/RoundRobinSpawner.cpp, Templates/Multiplayer/Template/Gem/Code/enabled_gems.cmake, Templates/Multiplayer/Template/default.blastconfiguration, Templates/Multiplayer/template.json, repo.json
We noticed that the Multiplayer template was in an unusable state. This fixes the two errors I ran into.
1. The Blast Gem had been moved to a now-stale Experimental branch. The template had included it as a dependency, causing Project Manager to throw up errors about it being missing. Removing the references to the Blast Gem fixes this.
2. Once past that, it wouldn't build at all, choking on an explicit template function call, despite the types matching. Removing the types in the call fixes this.
Manual.
To test:
1. Download the Multiplayer template
2. Create a new project using it
3. It
- Should not give Blast errors
- Should build without error
- Should run a Game, start the Game Server, and connect to it without error
=> Make Multiplayer Template Usable Again

Gems/OpenXRVk/Code/Source/OpenXRVkUtils.cpp
Fixes C2220 errors and warnings for the `PrintXrError` function. Addresses: https://github.com/o3de/o3de-extras/issues/687
Tested in a separate branch
=> Add [[maybe_unused]] to PrintXrError parameters

Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.cpp
The release build of ROS2 Gem failed due to unused variable. 
Project centric, release build on ubuntu 22.04 with Ros2Project template.
=> Added [[maybe_unused]] to fix release build

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponentController.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponentController.h
Modifies the ROS2 spawner by: 
- Adding the option to set custom names for the spawner services (from the Editor)
- Adding a parent to the spawned entities that modifies the TF hierarchy in some scenarios.
- Extends functionality
- Add more flexibility
- Does not complicate implementation
Compared to the previous version, in the Editor the user can see `Service names` field
Tested on an external project and blank template project from o3de-extras. Tested by 
1. Open demo level and add ROS2 Spawner to the `Warehouse` entity
2. Add test prefab to rosbot spawner
3. Execute services on game mode 
4. Change service names and test again
=> ROS2 Spawner add setting parent TF and modifiable service names 

Gems/ROS2/Code/Tests/Frame/ROS2FrameComponentTest.cpp
Tests would not build with the more recent o3de `development` due to some changes in includes: 
```
[build] /home/jhanca/devroot/o3de-extras/Gems/ROS2/Code/Tests/Frame/ROS2FrameComponentTest.cpp:23:10: fatal error: 'AzToolsFramework/Commands/PreemptiveUndoCache.h' file not found
[build] #include <AzToolsFramework/Commands/PreemptiveUndoCache.h>
[build]          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] 1 error generated.
[build] ninja: build stopped: subcommand failed.
```
This PR fixes it by removing this include.
The code builds now correctly and the test passes.
```
[proc] Executing command: /usr/bin/ctest -j16 -C profile -T test --output-on-failure -R ^Gem\:\:ROS2\.Frame\.Tests\.main\:\:TEST_RUN$
[ctest]    Site: jhanca-buntu
[ctest]    Build name: Linux-clang++ …
```
=> Remove non-existing include in ROS2 tests

Gems/ROS2/Code/Source/Manipulation/JointsPositionsComponent.cpp
This fixes an issue where the joints positions command at the first index is sent to all joints, instead of their respective commands.
I do not know the preferred convention for dual range loop iteration in C++17 (which I believe is what O3DE targets) so feel free to make changes!
1. Build an engine from the `92df6b` PhysX Gem Split
2. Build a Ros2RoboticManipulationTemplate project from this PR
3. Added a JointsPositionsEditorComponent with J1-7  to panda_link0
4. Command `ros2 topic pub --once /position_controller/commands std_msgs/msg/Float64MultiArray "{data: [0.1, -0.69, 0.1, -2.26, 0.1, 1.47, 0.89]}"` (this is 0.1 rad from the default starting position) from another terminal with the simulator running
If you build the project from upstream, the arm will attempt to move all joints to …
=> Fix issue with position control index processing

Gems/ProteusRobot/Assets/Proteus.prefab, Gems/ROS2/Assets/Prefabs/Sensors/CameraOrbbeck.prefab, Gems/ROS2/Assets/Prefabs/Sensors/LidarOS2.prefab, Gems/WarehouseAssets/Assets/Prefabs/WarehouseScene.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox1.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox2.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox3.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox4.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseRack.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Misc/Movable_blue.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Rack_protectors/Rack_front_protector.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Rack_protectors/Rack_side_protector.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Storage_on_wheels.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Components/Ceiling_Lamp.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Warehouse_Floor.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Warehouse_Roof.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Warehouse_Walls.prefab
This PR updates prefabs in WarehouseAssets, ROS2/Assets, ProteusRobot to match changes introduced in o3de.
Using o3de: `92921487211bf1cf859027fedf076afafb43215e`
I created new project from `Ros2FleetRobotTemplate` and went through every prefab in listed Gems in order smallest to largest.
1. Instantiate prefab
2. Enter prefab editing mode
3. Ctrl + S
4. Remove prefab instance from level
Changes adding ...`.fbx`... are the result of [#16517](https://github.com/o3de/o3de/pull/16517)
Prefabs were manually verified that their visualizations didn't change.
=> Update ROS2 Related prefabs

repo.json
Recent updates to the `Ros2RoboticManipulationTemplate` was not reflected in repo.json, which causes an error trying to download the template from Project Manager that is built from the development branch. This update fixes that using the `o3de.sh edit-repo-properties` command line for the template.
Tested locally
=> repo.json updates for Ros2RoboticManipulationTemplate

Gems/ProteusRobot/gem.json, Gems/ROS2/gem.json, Gems/RosRobotSample/gem.json, Gems/WarehouseAutomation/gem.json
Update `gem.json` file of ROS2 Gem to allow the Gem use with stabilization branch (see the https://github.com/o3de/o3de/pull/17903) and fix the URLs.
Update other `gem.json` files in ROS2 related gems.
This change will be later cherry-picked to `o3de-extras/stabilization` branch.
the code was built against the `o3de/stabilization` branch and the errors like the following
```
[build]   RosRobotSample is incompatible because: o3de 2.3.0 does not match any
[build]   version specifiers in the list of compatible engines: ['o3de-sdk>=4.1.0',
[build]   'o3de>=4.1.0']
```
is gone
=> Update gem.json files of ROS2 related Gems

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponentController.cpp, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponentController.h
Added option in ROS2 Spawner component to spawn entities using WGS84 coords using existing spawn_entity service. To switch to WGS84 coords parameter 'reference_frame' needs to be set to 'wgs84'.
Usage example: ros2 service call /spawn_entity gazebo_msgs/srv/SpawnEntity "{name: 'some', xml: '', robot_namespace: '', initial_pose: { position: { x: 32.5896238486642, y: 35.1930592634115, z: 135.0 }, orientation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 } }, reference_frame: 'wgs84' }"
By using level with geo reference (made by @michalpelka) and spawning entities with different rotation,
=> Added option to spawn entities with WGS84 coords using existing ros service

Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.cpp
This PR prevents null pointer dereference when the ROS2 System component is deactivated at the start of the simulation in the editor.
#705 
Run against manipulation template with o3de/stabilization/2409
Note:
This is PR is crash-fix. ROS 2 functionality is partially usable in simulation mode. The ROS 2, sensors, and others are paused on the Editor's window loses focus. However, I think it is unrelated to ROS 2 and is some feature or bug in o3de.
=> Fix ROS 2 System component to work with Simulate in Editor

Gems/ROS2/Code/Include/ROS2/Georeference/GeoreferenceBus.h, Gems/ROS2/Code/Include/ROS2/Georeference/GeoreferenceStructures.h, Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.cpp, Gems/ROS2/Code/Source/Georeference/GeoreferenceLevelComponent.cpp, Gems/ROS2/Code/Source/Georeference/GeoreferenceLevelComponent.h, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/Code/Tests/GNSSTest.cpp
It simple change of name of a few methods. 
Some of the fields and methods were misspelled (it was WSG, it should be WGS).
Build localy, run the unit test.
=> Fix spelling in georeference.

Gems/ROS2/Code/Include/ROS2/ROS2SensorTypesIds.h, Gems/ROS2/Code/Include/ROS2/Sensor/Events/EventSourceAdapter.h, Gems/ROS2/Code/Include/ROS2/Sensor/ROS2SensorComponentBase.h, Gems/ROS2/Code/Include/ROS2/Sensor/SensorConfigurationRequestBus.h, Gems/ROS2/Code/Include/ROS2/Sensor/SensorHelper.h, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2CameraSensorComponent.h, Gems/ROS2/Code/Source/ContactSensor/ROS2ContactSensorComponent.cpp, Gems/ROS2/Code/Source/ContactSensor/ROS2ContactSensorComponent.h, Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.cpp, Gems/ROS2/Code/Source/GNSS/ROS2GNSSSensorComponent.h, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.cpp, Gems/ROS2/Code/Source/Imu/ROS2ImuSensorComponent.h, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.h, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h, Gems/ROS2/Code/Source/Odometry/ROS2OdometrySensorComponent.cpp, Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.cpp, Gems/ROS2/Code/Source/Odometry/ROS2WheelOdometry.h, Gems/ROS2/Code/Source/Sensor/SensorHelpers.cpp, Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.cpp, Gems/ROS2/Code/ros2_files.cmake, Gems/ROS2/Code/ros2_header_files.cmake
- Add and tested `SensorConfigurationRequestBus`
- Added helper functions to discover ROS 2 Sensors in runtime
- Moved ROS 2 Sensors types to `ROS2SensorTypesIds.h`
It is a fix of an existing feature - a bus `SensorConfigurationRequestBus` that allows adjusting the behavior of ROS 2 sensors.
It uses the ComponentEntityId pair as the key.
Also, a number of things were added or adjusted:
- Add and tested `SensorConfigurationRequestBus`
- Added helper functions to discover ROS 2 Sensors in runtime
- Moved ROS 2 Sensors types to `ROS2SensorTypesIds.h`
It is only API, that 3rd party needs to integrate. As test, I've implemented a Gem to test it:
https://github.com/RobotecAI/robotec-o3de-tools/pull/38
=> Update ROS 2 sensors base implementation

Gems/ProteusRobot/gem.json, Gems/ROS2/gem.json, Gems/RosRobotSample/gem.json, Gems/WarehouseAutomation/gem.json, Templates/Ros2FleetRobotTemplate/Template/project.json, Templates/Ros2FleetRobotTemplate/template.json, Templates/Ros2ProjectTemplate/Template/project.json, Templates/Ros2ProjectTemplate/template.json, Templates/Ros2RoboticManipulationTemplate/Template/project.json, Templates/Ros2RoboticManipulationTemplate/template.json, repo.json
Update ROS2 and related gems that were pointing to version 4.1.0 of the engine sdk to use the stabilization/2409 candidate version of 2.3.0 and add a new version of each of the updated gems.
The updated gems have been uploaded to 
* https://github.com/o3de/o3de-extras/releases/download/2.0/proteusrobot-2.0.0-gem.zip
* https://github.com/o3de/o3de-extras/releases/download/2.0/rosrobotsample-2.0.0-gem.zip
* https://github.com/o3de/o3de-extras/releases/download/2.0/warehouseautomation-2.0.0-gem.zip
The updated templates have been uploaded to 
* https://github.com/o3de/o3de-extras/releases/download/2.0/ros2fleetrobottemplate-2.0.0-template.zip
* https://github.com/o3de/o3de-extras/releases/download/2.0/ros2projecttemplate-2.0.0-template.zip
* …
=> Fix engine version dependencies for ROS2 and related gems for the o3de stabilization/2409 release

Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp
Closes #462
Now Lidar acquires data about raycast results even when publishing is disabled, making it possible to visualise results independently from publishing.
Even though issue #462 suggests otherwise, problem with visualisation seems to only apply to Lidar components and further corrections are unnecessary.
Tested on basic ROS2 project template using rviz2. Visualisation works independently from publishing (and vice-versa).
=> Lidar: Fixed data acquisition while publishing disabled

Gems/ProteusRobot/gem.json, Gems/RosRobotSample/gem.json, Gems/WarehouseAutomation/gem.json, Templates/Ros2FleetRobotTemplate/Template/project.json, Templates/Ros2FleetRobotTemplate/template.json, Templates/Ros2ProjectTemplate/Template/project.json, Templates/Ros2ProjectTemplate/template.json, Templates/Ros2RoboticManipulationTemplate/Template/project.json, Templates/Ros2RoboticManipulationTemplate/template.json, repo.json
Cherry picks fixes to gem and template versioning from https://github.com/o3de/o3de-extras/pull/718 into development
TBD
=> Cherry pick fix for engine version dependencies update

Gems/ROS2/gem.json, repo.json
This bumps the version of the ROS2 gem from version 3.1.0 -> 3.2.0 now that 3.1.0 is the candidate version for the upcoming O3DE 2409 release.
note: ROS2 version 3.2.0 has been uploaded to o3de-extras releases (https://github.com/o3de/o3de-extras/releases/download/2.0/ros2-3.2.0-gem.zip)
Tested configuring projects with ProjectManager
=> Bump minor version for ROS2 gem for the development branch

Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h, Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplateUtils.h
Closes #488 
Now Lidar converts data about raycast angles right after receiving them as input, instead of converting them only during performing raycast requests.
Tested on basic ROS2 project template using rviz2. Outputs correspond with previous version both for 2D and 3D Lidar components.
=> Lidar: Internal storage changed from Euler to quaternion

Gems/OpenXRVk/Code/Source/OpenXRVkSwapChain.cpp
Added support to do MSAA Resolve
directly on XR Swapchain Attachments by adding
XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT usage flag
to the XrSwapchainCreateInfo.
Also, matched Swapchain attachment usage flags
as done by Atom Vulkan library in
/o3de/Gems/Atom/RHI/VulkanCode\Source\RHI\SwapChain.cpp
```cpp
createInfo.imageUsage = VK_IMAGE_USAGE_TRANSFER_DST_BIT |
VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT |
VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT |
VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
```
The whole XR Swapchain creation usage flags changed from:
```cpp
swapchainCreateInfo.usageFlags = XR_SWAPCHAIN_USAGE_SAMPLED_BIT |
XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT;
```
to:
```cpp
swapchainCreateInfo.usageFlags = XR_SWAPCHAIN_USAGE_SAMPLED_BIT |
XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT | …
```
=> Added support to do MSAA Resolve

Gems/ROS2/Code/Include/ROS2/Manipulation/MotorizedJoints/JointMotorControllerComponent.h, Gems/ROS2/Code/Include/ROS2/Utilities/ROS2Conversions.h, Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsManipulationComponent.h, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.h, Gems/ROS2/Code/Source/Manipulation/MotorizedJoints/JointMotorControllerComponent.cpp, Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.cpp, Gems/ROS2/Code/Source/Utilities/ROS2Conversions.cpp
This PR changes number of places in codebase, where delta time is used.
In current development (and release) the delta time was taken from AZ::TickBus::OnTick.
That is a time between two OnTick. It is not simulation time.
I've changed code to get simulation time.
Build and run. The test effort should be part of https://github.com/o3de/o3de-extras/issues/710
=> Use simulation time to compute time difference.

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
This PR is a small fix for ROS2SpawnerComponent. The behavior of setting a parent Id of a spawnable might not work as intended, since the entity id is not yet attached during preinsertion callback.
Old behavior manifested itself as warnings in the log console:
The new behavior moves setting the parent into completion callback when the entity id is already well-defined.
It was tested in an internal project.
=> Fix bug in a spawner component

Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameConfiguration.h, Gems/ROS2/Code/Source/Frame/ROS2FrameConfiguration.cpp, Gems/ROS2/Code/Source/Frame/ROS2FrameSystemComponent.h, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h, Gems/ROS2/Code/Source/Lidar/LidarSystem.h, Gems/ROS2/Code/Source/Sensor/SensorConfiguration.cpp
Closes #159 
* Adds Info category in O3DE ROS2 Frame description, containing non-editable fields displaying namespace and full name of the Frame.
* Changes awkward category name in O3DE sensor editors to clearer "Publisher configuration".
* Adds and fixes some comments for doxygen documentation.
With namespace and frame names changes being applied, info category gets changed accordingly, displaying correct information.
=> Extend description of frames in o3de

Gems/RosRobotSample/Assets/ROSbot.prefab, Gems/RosRobotSample/gem.json, Templates/Multiplayer/Template/Gem/Source/${Name}Module.cpp, Templates/Ros2FleetRobotTemplate/Template/project.json, Templates/Ros2ProjectTemplate/Template/Gem/Source/${Name}EditorModule.cpp, Templates/Ros2ProjectTemplate/Template/Gem/Source/${Name}Module.cpp, Templates/Ros2ProjectTemplate/Template/Gem/Source/${Name}SampleComponent.cpp, Templates/Ros2ProjectTemplate/Template/project.json, Templates/Ros2RoboticManipulationTemplate/Template/Gem/Source/${Name}Module.cpp, Templates/Ros2RoboticManipulationTemplate/Template/Gem/Source/${Name}SystemComponent.cpp, Templates/Ros2RoboticManipulationTemplate/Template/Gem/Source/${Name}SystemComponent.h, Templates/Ros2RoboticManipulationTemplate/Template/project.json
This PR fixes multiple aspects of templates:
1. The templates were not using own Gems, which causes issues when some implementation matters (closes #722 )
2. Templates used to create the files that were named `{Name}Something.h`, but including `{Sanitized}Something.h`
3. ROSBot prefab parameters were set incorrectly, it was fixed based on the [specification](https://docs-new.s3.eu-west-1.amazonaws.com/pdf/ROSbot_XL_Overall_Dimensions.pdf)
4. Cherry-pick of #721 
Note: this PR conflicts with https://github.com/o3de/o3de-extras/pull/718 and cherry-picks changes from https://github.com/o3de/o3de-extras/pull/721 to reduce the number of conflicts and separate PRs doing the same
Templates were run.
=> Fixes for templates

Gems/ROS2/Code/Include/ROS2/Lidar/LidarRaycasterBus.h, Gems/ROS2/Code/Include/ROS2/Lidar/LidarRegistrarBus.h, Gems/ROS2/Code/Source/Lidar/LidarCore.cpp, Gems/ROS2/Code/Source/Lidar/LidarCore.h, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h
This pr introduces lidar intensity data support for the ROS2 Lidar Sensor Component (does not implement this feature for the ROS2 Lidar 2D Sensor Component) . It also modifies point-cloud publishing as intensity is an optional feature and may not be provided by every lidar implementation (eg. Scene queries). For more information about the intensity capabilities and component support see the [RGL gem intensity support pull request](https://github.com/RobotecAI/o3de-rgl-gem/pull/33).
_**Note:**_ _Due to https://github.com/o3de/o3de-extras/issues/719 and future [instance segmentation](https://github.com/o3de/o3de-extras/pull/713) integration this part of the ROS2 Lidar Sensor will soon have to be updated (see https://github.com/o3de/o3de-extras/issues/736)._
This feature was tested on Mesh …
=> [ROS2] Add support for lidar intensity

Gems/ROS2/Code/Source/Manipulation/JointsManipulationEditorComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsManipulationEditorComponent.h, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.h, Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2AckermannModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2CameraSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2GNSSSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2ImuSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2JointPoseTrajectoryModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2JointStatePublisherModelHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2LidarSensorHook.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2ModelPluginHooks.h, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/ROS2SDFormatHooksUtils.h, Gems/ROS2/Code/Source/RobotImporter/URDF/SensorsMaker.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp, Gems/ROS2/Code/Source/RobotImporter/Utils/RobotImporterUtils.h, Gems/ROS2/Code/Tests/SdfParserTest.cpp, Gems/ROS2/Code/ros2_editor_files.cmake
Adds functionality and fixes some minor bugs in Robot Importer feature:
* Adds GetPluginParams function, extracting parameters from ROS2 and ROS1 plugins, making it easier to read and parse plugins attached to components.
* Components are now imported with correct topic names.
* Frames are imported with correct names and namespaces.
* Adds libgazebo_ros_joint_state_publisher.so and libgazebo_ros_joint_pose_trajectory.so plugins handling.
* ROS1 lidar will be imported with correct update frequency (previously frequency was not imported as for ROS1 it's an element of a plugin which was not supported).
* While importing gnss and imu components, all necessary components will be added to the entity.
* After successful SDF/URDF importing, unsupported plugin parameters will be included in the …
=> RobotImporter features: topic names, namespaces, handling plugins, joints

Gems/ROS2/Code/Include/ROS2/Lidar/LidarRaycasterBus.h, Gems/ROS2/Code/Source/Lidar/LidarCore.cpp, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h, Gems/ROS2/Code/Source/Lidar/LidarTemplate.cpp, Gems/ROS2/Code/Source/Lidar/LidarTemplate.h
This PR simplifies `LidarRaycaster` range configuration (in preparation for #736). It also adds proper, editor-side range value validation.
This PR was developed alongside https://github.com/RobotecAI/o3de-rgl-gem/pull/40.
This pull request was tested in a simple test project under various lidar configurations.
=> Simplify and improve lidar range configuration

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
This PR cherry-picks the fix that was merged to `stabilization` branch back to the `development` branch. Please refer to #725 for details of the fix.
The code was built and the object was spawned correctly.
=> Cherry-pick: fix bug in a spawner component (#725)

Gems/ROS2/Code/Include/ROS2/Lidar/LidarRaycasterBus.h, Gems/ROS2/Code/Include/ROS2/Lidar/RaycastResults.h, Gems/ROS2/Code/Source/Lidar/LidarCore.cpp, Gems/ROS2/Code/Source/Lidar/LidarCore.h, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.cpp, Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h, Gems/ROS2/Code/Source/Lidar/PointCloudMessageBuilder.cpp, Gems/ROS2/Code/Source/Lidar/PointCloudMessageBuilder.h, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2Lidar2DSensorComponent.h, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.cpp, Gems/ROS2/Code/Source/Lidar/ROS2LidarSensorComponent.h, Gems/ROS2/Code/Source/Lidar/RaycastResults.cpp, Gems/ROS2/Code/ros2_files.cmake, Gems/ROS2/Code/ros2_header_files.cmake
This pull request features:
- Refactor of the Raycast Request class:
- results now are guaranteed to be the same size
- introducing new fields is now easier
- New ROS 2 pc message builder class
This PR aims to resolve #736.
Ran in multiple configurations (also with RGL gem) on a simple project.
=> [ROS2] Raycast Results Refactor

Gems/ROS2/Code/Source/Camera/CameraSensor.cpp
Allows to modify ROS 2 camera pipeline. It enables Diffuse Probe Grid.
Running level:
https://gist.github.com/michalpelka/e01d0ebe4cbbaf134fa5756839237b0b
Problems were resolved by https://github.com/o3de/o3de/pull/18254
~~There are multiple warnings in console:~~
```
(PhysX) - Failed to connect to the PhysX Visual Debugger (PVD).
(ROS2SystemComponent) - Enabling realtime clock
Entered game mode
(ROS2FrameComponent) - Setting up Entity6/sensor_frame
(ROS2FrameComponent) - Setting up dynamic transform between parent Entity6/odom and child Entity6/sensor_frame to be published continuously to /tf
(Spawnables) - Entities from new root spawnable 'Root.spawnable' are ready (generation: 0).
(PhysX) - Successfully disconnected from the PhysX Visual Debugger (PVD).
Exited game mode
(PhysX) - …
```
=> Enable ROS 2 camera pipeline modification

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
Cherry-pick of #760 to stabilization.
It fixes the issue within ROS 2 Spawner: O3DE crashes when spawning with undefined rotation. It used to be the user's responsibility to give correct data, but the check is straightforward and it could save from the crash.
Spawning with incorrect rotation was performed.
=> Add check for zero quaterion

Gems/ROS2/Code/Include/ROS2/Lidar/RaycastResults.h, Gems/ROS2/Code/Source/Lidar/PointCloudMessageBuilder.cpp
I've added missing includes that prevented non unity builds.
By compiling an example project.
=> Fix non unity build in lidar

Gems/ROS2/Code/Source/Frame/NamespaceConfiguration.cpp
This is a cherry-pick of a commit from #771 to fix a **blocker** issue #770 
The issue was raised on the multirobot setup with `ROS2SpawnerComponent`. `ROS2FleetTemplate` was used as an example - the change in #771 was tested successfully on the template; this PR is just a cherry-pick of the fix (excluding the changes in tests, as the goal is to minimize changes in the `stabilization` branch)
=> fix ROS2FrameComponent::UpdateNamespaceConfiguration()

Gems/ROS2/Code/Source/Frame/ROS2FrameEditorComponent.cpp
This PR allows adding ros2 frame to Level Entity, it allows for simplified level design when adding robots during simulation run. 
On 2409
1. Created new Level
2. Added ROS2 Frame on level entity
3. added robot to the level
4. Set robot top level tf to `publish tf on`
5. Verified tf tree in rqt-tf-tree
=> Allow ROS2 Frame Component to be present on Level Entity

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.cpp, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.h
This PR modifies `FollowingCameraComponent` to make it usable with `FlyCameraComponent`. In particular, it disables the keyboard capture in `FollowingCameraComponent`, when the selected camera entity contains `FlyCameraComponent`. That way only one component uses the keyboard captures and only one component changes the camera translation/rotation, making the behavior predictable and usable. 
Additionally, local camera rotation and local translation is reset after changing the camera.
Entity with `FollowingCameraComponent` was created and few other entities with `FlyCameraComponent` were liked to it. The system works as it should
=> Fix FollowingCameraComponent: allow fly camera

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Source/Camera/CameraSensor.cpp, Gems/ROS2/Code/Source/Frame/Conversions/FrameConversion.py, Gems/ROS2/Code/Source/Frame/NamespaceConfiguration.cpp, Gems/ROS2/Code/Source/Frame/ROS2FrameEditorComponent.cpp, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.cpp, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.h, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/gem.json, Projects/OpenXRTest/project.json, Templates/Multiplayer/template.json, Templates/Ros2FleetRobotTemplate/Template/Registry/ros2.setreg, Templates/Ros2FleetRobotTemplate/template.json, Templates/Ros2ProjectTemplate/Template/Registry/ros2.setreg, Templates/Ros2ProjectTemplate/template.json, Templates/Ros2RoboticManipulationTemplate/Template/Registry/ros2.setreg, Templates/Ros2RoboticManipulationTemplate/template.json, repo.json
This PR cherry-picks commits that should be included in the point release `2409.1`. This includes the following PRs with the following reasoning:
- #769 fixes version numbers of the project templates; it was pushed to the `stabilization/2409` branch **after** the release; it was used to generate the binary packages, but it was missing in the `main` branch
- #774 fixes the blocker issue that made custom namespaces unusable; it was pushed to the `stabilization/2409` branch **after** the release; it was used to generate the binary packages, but it was missing in the `main` branch
- #775 fixes ROS 2 Gem version; it was pushed to the `stabilization/2409` branch **after** the release; it was used to generate the binary packages, but it was missing in the `main` branch
- #772 improves the helper …
=> Cherry-picks for 2409.1 point release

Gems/ROS2/gem.json, Templates/Ros2FleetRobotTemplate/template.json, Templates/Ros2ProjectTemplate/template.json, Templates/Ros2RoboticManipulationTemplate/template.json, repo.json
Update repo versions and download packages for the ROS2 Gem and templates:
* ROS2 3.1.1 -> 3.2.2
Bumping minor and revision to baseline the release version numbers for ROS2. This number will represent the upcoming point-release and what will be in main. Will bump the development version to 3.3.0 moving forward
* Ros2FleetRobotTemplate, Ros2RoboticManipulationTemplate  
Bumping revision number to accommodate new ros setreg file in the template.
=> Update ROS2 Gem and template versioning for Point Release

Templates/Multiplayer/Template/Gem/Source/${Name}SystemComponent.cpp
Ensure Multiplayer gem is a requirement so that MultiplayerSystemComponent calls RegisterMultiplayerComponents before the project component activates.
It's important for multiplayer components to be registered in a consistent order so that the server and client assign the same component-id for each component.
Fixes #767
=> Fix Multiplayer Component Registration Order

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Source/Camera/CameraSensor.cpp, Gems/ROS2/Code/Source/Frame/Conversions/FrameConversion.py, Gems/ROS2/Code/Source/Frame/NamespaceConfiguration.cpp, Gems/ROS2/Code/Source/Frame/ROS2FrameEditorComponent.cpp, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.cpp, Gems/ROS2/Code/Source/SimulationUtils/FollowingCameraComponent.h, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/gem.json, Projects/OpenXRTest/project.json, Templates/Multiplayer/template.json, Templates/Ros2FleetRobotTemplate/Template/Registry/ros2.setreg, Templates/Ros2FleetRobotTemplate/template.json, Templates/Ros2ProjectTemplate/Template/Registry/ros2.setreg, Templates/Ros2ProjectTemplate/template.json, Templates/Ros2RoboticManipulationTemplate/Template/Registry/ros2.setreg, Templates/Ros2RoboticManipulationTemplate/template.json, repo.json
This PR merges fixes for o3de-extras for the 2409.1 point release. This includes the following PRs with the following reasoning:
- #784 Cherry-picks for fixes for the ROS2 Gem 
- #785 Versioning updates for the ROS2 Gem and Robotic Templates
Testing was done based on PR #784
=> Merge o3de extras point release 24091 to main

Templates/Multiplayer/Template/Gem/Source/${Name}Module.cpp
Adding client/server module gems in order to support monolithic (release export) builds
Fixes #788 
Created a new game using MultiplayerTemplate, opened ProjectManager and exported for Windows (monolithic enabeled)
=> Multiplayer Template Monolithic Build Fix

Gems/ROS2/Code/Source/Frame/Conversions/FrameConversion.py
The FrameConversion.py script is very helpful if you need to migrate your project to the 2409 release. However one thing is still missing, even with PR #772 - modifying `remove` operations in the `Patches` section is not handled properly. 
```
{
"op": "remove",
"path": "/Entities/Entity_[8678293627970]/Components/ROS2FrameComponent"
},
```
This PR extends the script capabilities - I think that now all cases are now covered.
By preparing nested prefab with the O3DE 2310, converted prefab with a script and used it with the O3DE 2409.
=> Added if statement for 'remove' operations in FrameConversion script

Templates/Ros2FleetRobotTemplate/Template/Gem/gem.json, Templates/Ros2FleetRobotTemplate/template.json, Templates/Ros2ProjectTemplate/Template/Gem/gem.json, Templates/Ros2ProjectTemplate/template.json, Templates/Ros2RoboticManipulationTemplate/Template/Gem/gem.json, Templates/Ros2RoboticManipulationTemplate/template.json
This fixes an issue where the dependency on the ROS2 gem fails whenever you create a project from one of the ROS2 templates and then add or remove additional gems from the project. 
When you create a new project from one of the ROS2 project templates, the default project Gem is added as the last item in project.json. It is preceded by the default gems for that particular template type, in which case ROS2 is one of the dependencies. The problem is, the CMakeLists.txt for the project gem has a call to `target_depends_on_ros2_packages`, which needs to be loaded before the gem is processed. Since the project gem is always last, the ROS2 gem will always get loaded first. 
But when you add or remove gems, Project Manager will, by default, order the list of enabled gems in alphabetical order. So …
=> Fix Gem dependency issue for  projects created from ROS2 templates

Gems/MachineLearning/Code/CMakeLists.txt, Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Source/Camera/CameraSensor.cpp, Gems/ROS2/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp, Gems/ROS2/gem.json, Templates/Ros2ProjectTemplate/Template/Gem/CMakeLists.txt, Templates/Ros2ProjectTemplate/template.json
PR https://github.com/o3de/o3de/pull/18405 changed target names in O3DE Gems, which caused build failures in o3de-extras. This is fixed in this PR.
Additionally:
- _ROS 2 Gem_ version was changed to newer than the last release (new features were added, non-breaking change, hence minor)
- _ROS 2 Gem_ was set to require _development_ version of o3de (it will not build otherwise)
- _Ros2ProjectTemplate_ version was changed to reflect changes in the cmake
A sample project was built with o3de from `development` branch, 0efe207e34
=> Fixes following o3de #18405

Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp, Gems/ROS2/Code/Source/RobotImporter/SDFormat/Hooks/ROS2SkidSteeringModelHook.cpp
Some variables in RobotImporter were used only for `AZ_Warning` macro, which is removed in _release_ builds. This was causing _unused_variable_ warnings, leading to a compilation failure. This is fixed now.
A release build was made.
=> Remove unused_variable warnings when release mode

Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.cpp, Gems/ROS2/Code/Source/Manipulation/FollowJointTrajectoryActionServer.h, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsTrajectoryComponent.h
This PR fixes state management when calling `JointsTrajectoryRequestBus`
Without this change, method 
```
class JointsTrajectoryRequests : public AZ::EBusTraits
...
//! Retrieve current trajectory goal status.
//! @return Status of trajectory goal.
virtual TrajectoryActionStatus GetGoalStatus() = 0;
```
Always returns `TrajectoryActionStatus::Idle` because `FollowJointTrajectoryActionServer` never receives any goals. 
This change effectively allows for using `JointsTrajectoryRequestBus` because without it. No movement will occur (cause of broken status in `JointsTrajectoryComponent::FollowTrajectory`)
`JointsTrajectoryRequestBus` was called in two ways.
1. Directly from cpp code by `JointsTrajectoryRequestBus::EventResult`
2. From ros2 via ros2 action server and …
=> Move Joint Tracjectory State to TrajectoryComponent

Projects/OpenXRTest/Gem/enabled_gems.cmake, Projects/OpenXRTest/project.json
Remove unused AWS core gem from OpenXRTest
Need for Jenkins to build https://github.com/o3de/o3de/pull/18571/
Built OpenXRTest using a o3de branch without AWS gems
Check AssetProcessor for any failed lua/scriptscanvas assets which may have been using AWS 
Unfortunately, there were a lot of shader/material asset errors and a fatal "RPI System could not initialize" error on Editor startup, but this occurred in vanilla development branch as well as the AWS removal branch
=> Remove Unused AWS Gem from OpenXRTest

Gems/ROS2/Code/Include/ROS2/Spawner/SpawnerBus.h, Gems/ROS2/Code/Include/ROS2/Spawner/SpawnerBusHandler.h, Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp, Gems/ROS2/Code/ros2_header_files.cmake
This PR adds a bus to the spawner component that notifies other components about spawns.
By spawning and despawning entities and listening on the bus with a custom component.
=> Add notification bus to spawner

Gems/ROS2/Code/Include/ROS2/ROS2GemUtilities.h, Gems/ROS2/Code/Source/Frame/ROS2FrameComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointUtils.cpp, Gems/ROS2/Code/Source/Manipulation/JointUtils.h, Gems/ROS2/Code/Source/Manipulation/JointsManipulationEditorComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsPositionsEditorComponent.cpp, Gems/ROS2/Code/ros2_editor_files.cmake
Add a vector clear when scanning for joints. In addition a check for joint type was added to prevent adding fix joints. Fixes #812.
By creating joints and clicking the scan button.
=> Fix bug where joints werent clearing in  JointPositionEditorComponent

Gems/ROS2/Code/Source/Odometry/ROS2OdometrySensorComponent.cpp, Gems/ROS2/Code/Source/Odometry/ROS2OdometrySensorComponent.h
This PR prevents user from getting a crash when adding `ROS2OdometrySensor` and `Articulation Link` into the same entity, see #816 
This is a simple fix that adds `Articulation Link` to the incompatible service. `ROS2OdometrySensor` using the link should be implemented as a proper solution to #816
Tried to add the `Articulation link`. Before (left) and after (right):
=> Disable ROS2OdometrySensor for Articulation links

Templates/Multiplayer/Template/Gem/CMakeLists.txt
Only build server modules if PAL_TRAIT_BUILD_SERVER_SUPPORTED. This was discovered building for Android when GameLift was enabled. The GameLift gem properly skips building GameLiftServer module if PAL_TRAIT_BUILD_SERVER_SUPPORTED
#Fixes https://github.com/o3de/o3de/issues/18638
Created a new project based on this template, enabled AWSGameLift gem, and added build dependency to AWSGameLift.Server.Static. Configured a project for Android, see that configure is now successful.
=> Skip Server Modules If Not PAL_TRAIT_BUILD_SERVER_SUPPORTED

Gems/ROS2/Code/Source/Camera/CameraSensor.cpp, Gems/ROS2/Code/Source/Camera/CameraSensor.h
Currenty the ros2 cameras view was aliased to the main game camera. This enabled the PostProcessFeatureProcessor to works with the ROS2 camera. This aliasing was done during camera activation, but if the main camera was not activated the ROS2 camera aliased to a wrong view (probably the old editor view). To fix this issue I've added the Camera Notification Bus handler to the ROS2 camera. It sets the alias when the main camera view changes.
By adding a ROS2 camera and fog component and checking if the fog is visible in the topic. I've also verified different this behaviour with different activation orders (1st o3de camera, 2nd ros2 camera and 1st ros2 camera, 2nd o3de camera)
=> Fix PostProcessFeatureProcessor view aliasing in ROS2 camera

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Include/ROS2/Utilities/Controllers/PidConfiguration.h, Gems/ROS2/Code/Source/Utilities/Controllers/PidConfiguration.cpp, Gems/ROS2/Code/Tests/PIDTest.cpp, Gems/ROS2/Code/ros2_tests_files.cmake
Removes the "control_toolbox" dependency.
PR with documentation update: https://github.com/o3de/o3de.org/pull/2641
- Unit tests provided (based on tests from previous implementation).
- Organoleptic test on local project with robot steered via Ackermann control (that uses PID underneath)
=> PID direct implementation. Removed control_toolbox dependency.

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
The `/get_available_spawnable_names` service in `ROS2 Spawner` always returned `success=False` in response, while there were no issues in calling the service. This PR adds setting the `success` field to `true` in the appropriate method.
A scene with ROS2 Spawner was loaded and played in the editor and the service was called:
```
$ ros2 service call /get_available_spawnable_names gazebo_msgs/srv/GetWorldProperties
requester: making request: gazebo_msgs.srv.GetWorldProperties_Request()
response:
gazebo_msgs.srv.GetWorldProperties_Response(sim_time=0.0, model_names=['tomato', 'green_cube', 'apple', 'blue_cube', 'corn', 'toy_box', 'carrot', 'red_cube', 'yellow_cube'], rendering_enabled=False, success=True, status_message='')
```
=> Add service success setting in ROS2SpawnerComponent::GetAvailableSpawnableNames

Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
Cherry-pick of the one-liner fix from #828 
The output value was never initialized, hence always returning `false`.
Tested as in PR #828, this PR was build
=> Add service success setting in GetAvailableSpawnableNames

Gems/ROS2/Code/CMakeLists.txt, Gems/ROS2/Code/Include/ROS2/Utilities/Controllers/PidConfiguration.h, Gems/ROS2/Code/Source/Utilities/Controllers/PidConfiguration.cpp, Gems/ROS2/Code/Tests/PIDTest.cpp, Gems/ROS2/Code/ros2_tests_files.cmake
This PR cherry-picks the changes from #825 to the *point release branch*.  The change is caused by the fact, that `control toolbox` library in ROS 2 framework has unstable API, causing many problems. This dependency was completely removed - it was unnecessary from the start, because only a small part of the library was used. This part was reimplemented, alongside with tests. The API in ROS 2 is unchanged. 
The trigger for this PR was the latest build with ROS 2 Jazzy:
```
In file included from /home/jhanca/devroot/projects/TestProject/build/linux/External/ROS2-5feff446/Code/CMakeFiles/ROS2.Static.dir/Unity/unity_9_cxx.cxx:19:
/home/jhanca/devroot/2409/o3de-extras/Gems/ROS2/Code/Source/Utilities/Controllers/PidConfiguration.cpp:73:15: error: 'initPid' is deprecated: Use initialize() …
```
=> Cherry-pick PID rework #825

Gems/ROS2/gem.json, Gems/RosRobotSample/Assets/ROSbot.prefab, Gems/RosRobotSample/gem.json, Templates/Ros2FleetRobotTemplate/template.json, Templates/Ros2ProjectTemplate/template.json, Templates/Ros2RoboticManipulationTemplate/template.json, repo.json
1. Fix ROSBot prefab: missing parent entity
2. Bump versions of robotic gems and templates
3. Update repo.json for the release
The versions are changed as follows:
- `ROS 2 Gem` version 3.2.2 -> 3.2.3
- `RosRobotSample Gem` version 2.0.1 -> 2.0.2
- `Ros2FleetRobotTemplate` version 2.0.2 -> 2.0.3
- `Ros2ProjectTemplate` version 2.0.2 -> 2.0.3
- `Ros2RoboticManipulationTemplate` version 2.0.1 -> 2.0.2
Note, that this is a final PR for this point release from the *sig-simulation* point of view. Release files were uploaded as a part of this PR.
Three templates and two gems were pulled from the release and verified (gem.json; template.json).
=> Bump versions of robotic gems and templates

Gems/ROS2/Code/Include/ROS2/Clock/ROS2Clock.h, Gems/ROS2/Code/Include/ROS2/ROS2Bus.h, Gems/ROS2/Code/Include/ROS2/Sensor/Events/EventSourceAdapter.h, Gems/ROS2/Code/Include/ROS2/Sensor/Events/PhysicsBasedSource.h, Gems/ROS2/Code/Include/ROS2/Sensor/Events/TickBasedSource.h, Gems/ROS2/Code/Source/Sensor/Events/PhysicsBasedSource.cpp, Gems/ROS2/Code/Source/Sensor/Events/TickBasedSource.cpp, Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.cpp, Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.h
This PR fixes two minor things in sensors triggering:
- it reintroduced removed by this PR median filter for FPS. It will prevent drops in camera frequency without frame limiter, as explained in #804 .
- it uses selected ROS 2 time source to trigger sensors, what  will resolve #805 
It was cherry picked against stable and tested in response to #804.
I've used test branch that logs sensor triggers (https://github.com/RobotecAI/o3de-extras/tree/mp/trigger_noted)
And script to visualize : https://gist.github.com/michalpelka/3f2c66f16d20ba714c6389d5cd173032
Without filter:
With filtering
You can see that triggers fro camera (green dots) are spaced evenly for code using median filter.
**Note** this is minor issue, since it can cause:
- too low frequency use case without frame limiter and …
=> Use ROS 2 clock for sensor triggering

Gems/RosRobotSample/Assets/ROSbot.prefab, Gems/RosRobotSample/gem.json, repo.json
This PR reverts the change introduced in `ROSBotSample` Gem introduced in #831 which fixed the `cover_link` entity. Besides fixing the `cover_link` entity, the change introduces other problems. After some internal `sig-simulation` conversations, the decision was to revert it. It is better to have an incorrect fixed joint than a stationary robot.
`git diff ` was used to check if the change in the Gem was reverted and if the change in `repo.json` was correctly reverted.
=> Revert ROSBotSample Gem 2.0.2 release

Gems/ROS2/Code/Source/Gripper/FingerGripperComponent.cpp, Gems/ROS2/Code/Source/Gripper/FingerGripperComponent.h
This PR adds an editor field allowing to change the initial position of the gripper in the FingerGripperComponent, which was previously hardcoded as `0.0f`. This would cause issues if the controller made a small error and set the position to a negative value close to zero - when trying to execute any trajectory using moveit, it would complain about it with the following error and reject to execute it:
In the ROS2 Robotic Manipulation template, in the Finger Gripper Component of the manipulator, various values were put into the "initial position" field and the gripper was put in those positions correctly when starting game mode.
=> Add gripper's initial position setting in FingerGripperComponent

Gems/ProteusRobot/CMakeLists.txt, Gems/ProteusRobot/gem.json, Gems/RosRobotSample/Assets/ROSBot_slamtec.prefab, Gems/RosRobotSample/Assets/ROSbot.prefab, Gems/RosRobotSample/Assets/ROSbot_velodyne.prefab, Gems/RosRobotSample/CMakeLists.txt, Gems/RosRobotSample/gem.json, Gems/WarehouseAssets/CMakeLists.txt, Gems/WarehouseAssets/gem.json, Gems/WarehouseSample/Assets/O3DEScene/Prefabs/Warehouse.prefab, Gems/WarehouseSample/CMakeLists.txt, Gems/WarehouseSample/gem.json
This PR fixes multiple small issues found when testing simulation Gems before the `2409.2` point release, please see #822 for details.
- `cover_link` entity in `ROSbot` prefabs in `RosRobotSample` Gem are now linked to the `body_link` entity, which makes them move correctly
- meshes in prefabs in `RosRobotSample` Gem are now correctly defined in _assethints_ (hence some overrides could have been removed)
- meshes in prefabs in `WarehouseSample` Gem are now correctly defined in _assethints_
- `CMakeLists.txt` files of asset-only simulation Gems were regenerated using O3DE 2410.x to ensure there are no problems with linking (see #837 for details)
`ROS2ProjectTemplate` was built with the newest version of Gems and tested.
Tested using #841  against O3DE `9b8d468f64` _stabilization/25050_
=> Small fixes for Gems

Gems/LevelGeoreferencing/CMakeLists.txt, Gems/LevelGeoreferencing/Registry/assetprocessor_settings.setreg, Gems/LevelGeoreferencing/gem.json
The `LevelGeoreferencing` Gem was first created as `Georeferencing` Gem and renamed afterward, but not all names were changed. This resulted in a warning printed in all projects using this Gem:
```
[Warning] (LocalFileIO::ResolveAlias) - Failed to resolve an alias: @GEMROOT:Georeferencing@/Assets
[Warning] (LocalFileIO::ResolveAlias) - Failed to resolve an alias: @GEMROOT:Georeferencing@/Registry
[Warning] (AssetDatabase) - Load time threshold exceeded: LoadAssetData call for translationassets/types/ondemandreflectedtypes.names took 162 ms to load 4010690 bytes (  0.0000 KB/s)
```
This warning was fixed by adding missing renames.
The project was built and no warning message can be seen. 
Tested against O3DE `9b8d468f64` _stabilization/25050_
=> Fix Georeferencing rename

Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameEditorComponent.h, Gems/ROS2/Code/Source/Frame/ROS2FrameEditorComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsManipulationEditorComponent.cpp, Gems/ROS2/Code/Source/Manipulation/JointsPositionsEditorComponent.cpp
This PR  fixes few issues with articulation in ROS 2:
- Invalid default for topic name for JointsPositionsEditorComponent
- "Find all values" button gives correct values for : JointsManipulationEditorComponent, JointsPositionsEditorComponent
- Add undo batch to trigger prefab modification.
- I've created articulation from scratch
- Added JointsManipulationEditorComponent and JointsPositionsEditorComponent
- Clicked "Find all values" for both components
- Saved prefab
- tested two components.
=> Fix of three minor bugs in Articulations in ROS 2 gem:

Gems/ROS2/Code/Source/ROS2ModuleInterface.h
Fixes double-free style error in ROS 2 Gem.
This is imprtant since:
- prevent unloaind of ROS2 Gem in gem test environment,
- It triggered UB on app exit.
This bug-fix part of other PR (to development):
https://github.com/o3de/o3de-extras/pull/852
I've fixed issue working on on other branch - it allowed to load and unload ROS 2 in test environment. 
It closes without any breakpoints, asserts, errors with '-rhi=null'.
**Note**
Built application still experience UB from Vulkan, this PR won't fix it.
```
System: Trace::Assert
/home/michalpelka/github_develop/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/Vulkan.h(142): (130870476277312) 'void AZ::Vulkan::AssertSuccess(VkResult)'
System: ASSERT: Vulkan API method failed: Device lost
System: ------------------------------------------------
System: …
```
=> The `ROS2CameraSensorComponent` was reflected twice

Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp
There was UB when API user tried to remove Simulation Entity twice.
Manual test with https://github.com/michalpelka/q_simulation_interfaces
=> Fix undefined behavior in removal already removed simulated entities.

Gems/ROS2/Code/Source/Camera/ROS2CameraSystemComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2CameraSystemComponent.h, Gems/ROS2/Code/Source/Camera/ROS2EditorCameraSystemComponent.cpp, Gems/ROS2/Code/Source/Camera/ROS2EditorCameraSystemComponent.h, Gems/ROS2/Code/Source/ROS2ModuleInterface.h, Gems/ROS2/Code/Source/SystemComponents/ROS2SystemComponent.cpp
Addresses two issues:
- double reflection of one of components
- setting RPISystem as optional for ROS2SystemCameraComponent allowing to load ROS2 gem in test environment.
I've wrote a test and it setup and teardown correctly:
https://gist.github.com/michalpelka/3ed21a2ef91683c375978770bfdbf44f
=> Adjustments to ROS 2 gem interface and system components.

Gems/SimulationInterfaces/Code/Include/SimulationInterfaces/SimulationEntityManagerRequestBus.h, Gems/SimulationInterfaces/Code/Source/Clients/ConsoleCommands.inl, Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp, Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.h, Gems/SimulationInterfaces/Code/Tests/Tools/SimulationIterfaceAppTest.cpp, Gems/SimulationInterfacesROS2/Code/Source/Services/SpawnEntityServiceHandler.cpp, Gems/SimulationInterfacesROS2/Code/Tests/Tools/Mocks/SimulationEntityManagerMock.h
Add option allow renaming to spawn service
Added integration test scenario,
Manual tests with https://github.com/michalpelka/q_simulation_interfaces
=> Add allow renaming option to Simulation Interface spawner

Gems/ROS2/Code/Include/ROS2/Clock/ITimeSource.h, Gems/ROS2/Code/Include/ROS2/Clock/ROS2Clock.h, Gems/ROS2/Code/Include/ROS2/Clock/ROS2TimeSource.h, Gems/ROS2/Code/Include/ROS2/Clock/RealTimeSource.h, Gems/ROS2/Code/Include/ROS2/Clock/SimulationTimeSource.h, Gems/ROS2/Code/Source/Clock/ROS2Clock.cpp, Gems/ROS2/Code/Source/Clock/ROS2TimeSource.cpp, Gems/ROS2/Code/Source/Clock/RealTimeSource.cpp, Gems/ROS2/Code/Source/Clock/SimulationTimeSource.cpp, Gems/SimulationInterfaces/Code/Include/SimulationInterfaces/SimulationEntityManagerRequestBus.h, Gems/SimulationInterfaces/Code/Include/SimulationInterfaces/SimulationMangerRequestBus.h, Gems/SimulationInterfaces/Code/Source/Clients/ConsoleCommands.inl, Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp, Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.h, Gems/SimulationInterfaces/Code/Source/Clients/SimulationManager.cpp, Gems/SimulationInterfaces/Code/Source/Clients/SimulationManager.h, Gems/SimulationInterfaces/Code/Tests/Tools/SimulationInterfaceTests.cpp, Gems/SimulationInterfaces/Code/Tests/Tools/SimulationIterfaceAppTest.cpp, Gems/SimulationInterfacesROS2/Code/Source/Clients/SimulationInterfacesROS2SystemComponent.cpp, Gems/SimulationInterfacesROS2/Code/Source/Clients/SimulationInterfacesROS2SystemComponent.h, Gems/SimulationInterfacesROS2/Code/Source/Services/ResetSimulationServiceHandler.cpp, Gems/SimulationInterfacesROS2/Code/Source/Services/ResetSimulationServiceHandler.h, Gems/SimulationInterfacesROS2/Code/Tests/Tools/Mocks/SimulationEntityManagerMock.h, Gems/SimulationInterfacesROS2/Code/simulationinterfacesros2_private_files.cmake
This PR implements  [reset simulation service ](https://github.com/ros-simulation/simulation_interfaces/blob/main/srv/ResetSimulation.srv)
- Added integration tests and unit tests for removal of spawned entities
- Manual testing using https://github.com/michalpelka/q_simulation_interfaces
=> Simulation interfaces - reset simulator service

Gems/SimulationInterfaces/Code/CMakeLists.txt, Gems/SimulationInterfaces/Code/Include/SimulationInterfaces/Result.h, Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp, Gems/SimulationInterfaces/gem.json, Gems/SimulationInterfacesROS2/Code/Tests/Tools/InterfacesTest.cpp
Alternative approach to https://github.com/o3de/o3de-extras/pull/864
That introduced dependency in SimulationInterface to ROS 2 gem and Simulation Interfaces message package
Unit tests.
=> [Simulation Interfaces] Adjust error code type - ROS2 way, setting frames

Gems/SimulationInterfacesROS2/Code/Source/Services/SpawnEntityServiceHandler.cpp, Gems/SimulationInterfacesROS2/Code/Source/Services/SpawnEntityServiceHandler.h, Gems/SimulationInterfacesROS2/Code/Tests/Tools/InterfacesTest.cpp
Adds regex to validate namespace and name.
Rebase and merge on top of https://github.com/o3de/o3de-extras/pull/865
- Added and run unit tests 
- q_simulation_interface:
=> [Simulation Interfaces] Validate Namespace and name 

Gems/SimulationInterfacesROS2/Code/Tests/Tools/InterfacesTest.cpp, Gems/SimulationInterfacesROS2/Code/Tests/Tools/Mocks/SimulationManagerMock.h, Gems/SimulationInterfacesROS2/Code/simulationinterfacesros2_editor_tests_files.cmake
This PR adds tests to check communication correctness between ROS 2 interfaces and the mocked O3DE buses.
By running SimulationInterfacesROS2 tests.
=> [Simulation Interfaces] Added simple test for the SimulateSteps action

Gems/SimulationInterfaces/Code/Source/Clients/SimulationManager.cpp, Gems/SimulationInterfaces/Code/Source/Clients/SimulationManager.h
PR fixes wrong simulation state after resetting it.
Manual calling to the `/set_simulation_state`, `/get_simulation_state` and `/reset_simulation`
=> [Simulation interfaces] Fix for wrong simulation state after reset

Gems/SimulationInterfaces/Code/Tests/Tools/InterfacesTest.cpp
It makes a little more intelligent (rather less dumb) test fixture, that waits for future to be ready.
Executed tests.
=> Added SpinUntilFuture to test fixture

Gems/SimulationInterfaces/Registry/SimulationInterface.Editor.setreg, Gems/SimulationInterfaces/Registry/SimulationInterface.setreg
The  SimulationInterfaces.Editor has system components that prevented loading tools like Material editor.
- Run Editor (**libSimulationInterfaces.Editor.so** loaded, functionality available)
- Run Material Editor (**libSimulationInterfaces.Editor.so** not loaded)
- Run GameLauncher (**libSimulationInterfaces.so** loaded, functionality available)
- Run tests.
=> Prevent loading SimulationInterface.Editor in other tools than Editor.

Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp, Gems/SimulationInterfaces/Code/Source/Tools/SimulationEntitiesManagerEditor.cpp, Gems/SimulationInterfaces/Code/Source/Tools/SimulationEntitiesManagerEditor.h
The spawned entity were leaking in Editor workflow. I've made sure to clean tickets on leaving game mode.
- spawn with simulation interface in Editor, leave game mode.
- Test.
=> [Simulation Interfaces] Reset tickets and cached information on deactivation of SimulationEntityManager

Gems/OpenXRVk/Assets/OpenXRVk/default.xractions, Gems/OpenXRVk/Code/CMakeLists.txt, Gems/OpenXRVk/Code/Source/Devices/Common/XRControllerAnimationsComponent.cpp, Gems/OpenXRVk/Code/Source/Devices/Common/XRControllerAnimationsComponent.h, Gems/OpenXRVk/Code/Source/Devices/Common/XRControllerComponent.cpp, Gems/OpenXRVk/Code/Source/Devices/Common/XRControllerComponent.h, Gems/OpenXRVk/Code/Source/Devices/Common/XRControllersConfig.cpp, Gems/OpenXRVk/Code/Source/Devices/Common/XRControllersConfig.h, Gems/OpenXRVk/Code/Source/OpenXRVkModule.cpp, Gems/OpenXRVk/Code/Source/Platform/Android/platform_private_android_files.cmake, Gems/OpenXRVk/Code/Source/Platform/Linux/platform_private_linux_files.cmake, Gems/OpenXRVk/Code/Source/Platform/Windows/platform_private_windows_files.cmake, Gems/OpenXRVk/Code/Source/XRCameraMovementComponent.cpp, Gems/OpenXRVk/Code/Source/XRInteractableComponent.cpp, Gems/OpenXRVk/Code/Source/XRInteractableComponent.h, Gems/OpenXRVk/Code/Source/XRRayInteractorComponent.cpp, Gems/OpenXRVk/Code/Source/XRRayInteractorComponent.h, Gems/OpenXRVk/Code/openxrvk_static_common_files.cmake, Gems/OpenXRVk_README_EN.md
OpenXRVk Gem doesn't contain any components to show VR controllers and/or to communicate with the objects in VR.
What was implemented:
- XRControllerComponent tracks the positions and the orientations of the controllers and displays them correctly in a VR scene
- XRControllerAnimationsComponent tracks the state of the control items (buttons, triggers, thumbsticks) on the VR controllers and performs according animations in VR scene
- XRControllersConfig allows to configure any controller of any manufacturer in the O3DE Editor
- XRRayInteractorComponent renders the ray from the controller, adjusts its length, changes its color and thickness when the ray hovers the XR Interactable Object
- XRInteractableComponent can be attached to any 3D object and that object can be dragged by the "drag …
=> Sources for new XRComponents for VR

Gems/SimulationInterfaces/Code/CMakeLists.txt
fixes: #911 
Adds Runtime dependencies to Simulation Interfaces test targets.
On empty project (without build artifacts) run:
```
cmake --build Project/build/linux --config profile --target SimulationInterfaces.Editor.Tests SimulationInterfaces.TestApp SimulationInterfaces.ROS2Tests
```
And run tests
```
ctest -C profile --verbose --output-on-failure --test-dir Project/build/linux --output-junit Testing/test-results.xml --tests-regex 'Gem::(SimulationInterfaces.Editor.Tests|SimulationInterfaces.TestApp|SimulationInterfaces.ROS2Tests)\.main'
```
Successful logs:
[logs.txt](https://github.com/user-attachments/files/20186960/logs.txt)
=> Added Runtime dependencies to Simulation Interfaces test targets

Gems/LevelGeoreferencing/gem.json, Gems/MachineLearning/gem.json, Gems/OpenXRVk/gem.json, Gems/ROS2/gem.json, Gems/ROS2SampleRobots/gem.json, Gems/SimulationInterfaces/gem.json, Gems/WarehouseAssets/gem.json, Gems/XR/gem.json, Templates/Multiplayer/template.json, Templates/Ros2ProjectTemplate/template.json, repo.json
This PR updates all necessary versions for the `2505.0` release.
The release files were already uploaded.
The changes in https://github.com/o3de/canonical.o3de.org will be uploaded after this PR receives an okay.
Details about all updates are below.
* **LevelGeoreferencing:** new Gem; added to the release
* **MachineLearning Gem:** linking to Atom_Feature_Common changed, forcing engine version change; the Gem needs a release and a version bump (patch)
* **OpenXRVk Gem:** updated build OpenXR dependency; the Gem needs a release and a version bump (minor)
* **ROS 2 Gem:** multiple updates; new API; linking updates forcing engine version change; the Geg's version on the `development` branch was bumped while development (changed order of fields in `gem.json` file to match the order in other …
=> Update `repo.json` and all `gem.json` for the release

Gems/ROS2/Code/Source/Frame/ROS2FrameEditorComponent.cpp, Gems/ROS2/Code/Source/Frame/ROS2FrameSystemBus.h, Gems/ROS2/Code/Source/Frame/ROS2FrameSystemComponent.cpp
Edit: The text was updated following the update of the code, as explained below.
The implementation in ROS2Gem was not available in AssetBuilder. That said, it was not able to activate the component due to the missing implementation when importing URDF/SDF files (it might want to do so, e.g., when baking cylinder mesh while importing colliders). As a result, the asset builder was not able to import the model. This PR adds a missing system component to the asset builder. 
- executed tests
- changed namespace types (empty/custom/entity_name) within the Editor a few times
- created an entity within another entity to verify that the parent namespace was read correctly
- moved the entity with a frame component between two different parents to verify that the parent namespace was read correctly
=> Add FrameSystemComponent to AssetBuilder

Gems/LevelGeoreferencing/gem.json, Gems/MachineLearning/gem.json, Gems/OpenXRVk/gem.json, Gems/ROS2/gem.json, Gems/ROS2SampleRobots/gem.json, Gems/SimulationInterfaces/gem.json, Gems/WarehouseAssets/gem.json, Gems/XR/gem.json, Templates/Multiplayer/template.json, Templates/Ros2ProjectTemplate/template.json, repo.json
Versions of the Gems and `repo.json` file were updated on the stabilization branch, the changes were cherry-picked back to the `development` branch in this PR. In particular, changes from #915 and #919 were ported back.
The diff between the branches (the only difference is in `OpenXRVk` and `ExternalProfilers` Gems, which is expected).
=> Port changes back stabilization/25050 -> development

Gems/ROS2SampleRobots/Assets/RosbotXL/ROSbotXL.prefab, Gems/ROS2SampleRobots/gem.json, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox1.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox2.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox3.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Components/WarehouseBox4.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_storage/Storage_on_wheels.prefab, Gems/WarehouseAssets/Assets/Prefabs/Warehouse_structural/Warehouse_Walls.prefab, Gems/WarehouseAssets/gem.json
This PR removes unnecessary, leftover material slot overrides from the Warehouse Assets gem's prefabs. This change is related to the new [RGL gem release](https://github.com/RobotecAI/o3de-rgl-gem/pull/81). Removed overrides referred to non-existent material slots.
Modified prefabs were tested in the editor to ensure proper material overrides. They were tested with the RGL gem active.
=> [WarehouseAssets] Remove leftover material slot overrides

Gems/SimulationInterfaces/Code/Source/Clients/SimulationManager.cpp, Gems/SimulationInterfaces/Code/Source/Clients/SimulationManager.h, Gems/SimulationInterfaces/Registry/simulationinterface_settings.setreg
This commit allows User to change simulation state with keyboard. There is possibility to set three transitions with registry:
```
{
"SimulationInterfaces": {
"PrintStateNameInGui": true,
"StartInStoppedState": true,
"KeyboardTransitions":
{
"StoppedToPlaying": "keyboard_key_alphanumeric_R",
"PausedToPlaying": "keyboard_key_alphanumeric_R",
"PlayingToPaused": "keyboard_key_alphanumeric_P"
}
}
}
```
It will:
show hint in UI, and will listen to keyboard inputs. Names if keyboard inputs are available `o3de/Code/Framework/AzFramework/AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard.h`
https://github.com/user-attachments/assets/9015e058-4642-43cc-8256-14731bf38496
- run unit tests (little one failed due to being flaky)
- test with GUI
- test with q_simulation_interfaces
=> [Simulation Interfaces] Add keyboard activated state transition

Gems/ROS2Controllers/Code/Source/RobotControl/Controllers/RigidBodyController/RigidBodyTwistControlComponent.cpp, Gems/ROS2Controllers/Code/Source/RobotControl/Controllers/RigidBodyController/RigidBodyTwistControlComponent.h
Prevent the user from shooting their foot with one of RigidBodyTwistControlComponent.
By shooting own foot.
=> Adjust compatible services for RigidBodyTwistControlComponent

Gems/SimulationInterfaces/Code/Source/Actions/ROS2ActionBase.h, Gems/SimulationInterfaces/Code/Source/Clients/ROS2SimulationInterfacesSystemComponent.cpp, Gems/SimulationInterfaces/Code/Source/Clients/ROS2SimulationInterfacesSystemComponent.h, Gems/SimulationInterfaces/Code/Source/Interfaces/IROS2HandlerBase.h, Gems/SimulationInterfaces/Code/Source/Services/GetSimulationFeaturesServiceHandler.h, Gems/SimulationInterfaces/Code/Source/Services/GetSimulatorFeaturesServiceHandler.cpp, Gems/SimulationInterfaces/Code/Source/Services/GetSimulatorFeaturesServiceHandler.h, Gems/SimulationInterfaces/Code/Source/Services/ROS2ServiceBase.h, Gems/SimulationInterfaces/Code/Source/Utils/RegistryUtils.cpp, Gems/SimulationInterfaces/Code/Source/Utils/RegistryUtils.h, Gems/SimulationInterfaces/Code/Tests/Tools/InterfacesTest.cpp, Gems/SimulationInterfaces/Code/simulationinterfaces_private_files.cmake, Gems/SimulationInterfaces/gem.json
This PR adds possibility for selective disabling of ROS 2 services/actions related to Simulation Interfaces. If user assigns empty string as a name of a service via settings registry, this service will not be created. It also won't be present in `/get_simulation_features` service.
This PR also changes `GetSimulationFeaturesServiceHandler::TypeName` to make it consistent with the rest of the code and documentation. In the rest of the code `TypeName` is assigned based on ROS 2 service/action name written in UpperCammelCase. I case of mentioned `TypeName` there was typo and instead of `GetSimulatorFeatures`, there was `GetSimulationFeatures`. Consistency is important since `TypeName` is used as settings registry key.
It was built in non-unity and available services were gathered via `ros2 …
=> [Simulation Interfaces] Added possibility to disable ROS 2 service/action

Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameComponent.h, Gems/ROS2/Code/Include/ROS2/Frame/ROS2FrameConfiguration.h, Gems/ROS2/Code/Source/Frame/ROS2FrameComponent.cpp, Gems/ROS2/Code/Source/Frame/ROS2FrameConfiguration.cpp, Gems/ROS2/gem.json
This PR adds an additional switch to the `ROS 2 Frame` component that forces it to be a dynamic frame. This option is disabled by default.
I used different prefabs with ROS 2 frames, changed their configuration (mainly the dynamic force switch), and checked:
- rviz2
- `/tf` topic
- `/tf_static` topic
=> Added "Force dynamic" switch to the ros2 frame component

Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp
The scale was cleared to one, when state of entity was applied.
I've fixed this issue in project I worked on.
=> [Simulation Interfaces] Do not change applied state on set_entity_state request.

Gems/SimulationInterfaces/Code/Source/Clients/LevelManager.cpp
PR fixes exporting of the project with added SimulationInterfaces Gem
I exported project in unity and non-unity build
=> Fix for broken project export

Gems/SimulationInterfaces/Code/Include/SimulationInterfaces/SimulationEntityManagerRequestBus.h, Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.cpp, Gems/SimulationInterfaces/Code/Source/Clients/SimulationEntitiesManager.h, Gems/SimulationInterfaces/Code/Source/Services/SpawnEntityServiceHandler.cpp, Gems/SimulationInterfaces/Code/Tests/Tools/InterfacesTest.cpp, Gems/SimulationInterfaces/Code/Tests/Tools/Mocks/SimulationEntityManagerMock.h, Gems/SimulationInterfaces/Code/Tests/Tools/SimulationIterfaceAppTest.cpp
This PR adds possibility to pass preinsertion callback to spawnEntity bus
non unity build,
run existing test
=> [Simulation Interfaces] Added presinsertion callback to spawnEntity

Gems/SimulationInterfaces/Code/CMakeLists.txt
PR adds required version for simulation_interfaces package since new version of gem requires it.
built with simulation_interfaces 1.0.1 ->fail of cmake config
built with simulation_interfaces 1.1.0 -> success
=> [Simulation interfaces] Added required version for simulation_interfaces package

Gems/ROS2/Code/CMakeLists.txt, Gems/SimulationInterfaces/Code/CMakeLists.txt
PR adds linking of `simulation_interfaces` package to API target to allow user to use `Gem::SimulationInterfaces.API` without additional linking to `simulation_interfaces` in code.
_Please describe any testing performed._
non-unity build
run existing tests
=> [Simulation Interfaces] Added linking of simulation_interfaces to API target

Gems/ROS2Controllers/Code/Tests/PIDTest.cpp
PR #988 changed the PID implementation to allow the negative values. The tests were not updated and they started failing. This is fixed now.
Tests were run.
=> Fix PID tests after #988
